### ISSUE TITLE
Enhancement add instant reminder into Email subject

### ISSUE THREAD

**Issue by KarlosFanta** [mikeberger/borg_calendar#11]
please also add:
Email Subject:  Reminder detail of what is happening now:
 (eg. 8am reminder: BORG reminder: "Walk dog" in subject of email.)
(i.e. please make email reminder look similar to popup reminder.)
Also: BORG Email Reminder Notice: Currently hourly reminders show up unsorted:
eg. Appointments for 18 Nov 2014
13:00 refill
08:00 Walk dog
19:00 Report Faults
09:30 test your phone

please sort by time.

**Comment by mikeberger** [comment]
Closing this old issue. Syncing with Caldav is still the way to get individual reminders to a reminder/todo program on IOS or Android. For Android, OpenTasks and aCalendar+ are good.
The next release of BORG will also sync with google calendar and tasks, eliminating the need for a caldav server.

I doubt the OP is still using BORG after 8 years. Just being thorough in closing this one...
