### ISSUE TITLE
CALDAV Sync is not working  And Give Incorrect  Error Message 

### ISSUE THREAD

**Issue by Hamadullah3592** [mikeberger/borg_calendar#111]
**Description:**
The CALDAV Can't working and Its can't give the understandable Error Message And no any another option to resolve this problem. 

**Steps to reproduce:**
> GO TO Navigation Bar
> Click On Lcal Button 
>Click On CALDAV Button
>Click On Sync CALDAV   

**Expected result:**
The Message Must Be Understandable and the Button could be redirect to the CALDAV Setting and another option that are  work like this.   

**Screenshots:**
<img width="960" alt="bug 7" src="https://user-images.githubusercontent.com/73606257/117551154-b92b4580-b05d-11eb-9736-fccdaf5eea15.PNG">

**Comment by mikeberger** [comment]
the message is clear. you cannot sync with a caldav server unless you set the proper options - like server address, name, password, etc....
adding a mechanism to have error popups redirect to the settings is not worth the effort. it takes 2 mouse clicks to open the settings.
