### ISSUE TITLE
SEARCH Button Is Irresponsible Button

### ISSUE THREAD

**Issue by Hamadullah3592** [mikeberger/borg_calendar#112]
Description:
The Search Button Is Not working and Not give any Error message. 

Steps to reproduce:
> GO TO Navigation Bar
> Click On Search
> Click On Search String
> Write in Search String Column That you want to search  
> Click On Search Button 

Expected result:
The Search Button Can't Search Anything But If Can't search At Least It give Any error relative to search string.

Screenshots:
<img width="960" alt="Bug 5" src="https://user-images.githubusercontent.com/73606257/117552153-2ee5e000-b063-11eb-9fe4-2ba5bf79c9bc.PNG">

**Comment by mikeberger** [comment]
will add a popup if there are no search results.
