### ISSUE TITLE
Export And Import Perfencess Not working  

### ISSUE THREAD

**Issue by Hamadullah3592** [mikeberger/borg_calendar#113]
**Description:**
If You export or Import And file Then they give Error "Access is denied" and error message is very complex.

**Steps to reproduce:**
> GO TO Navigation Bar
> Click On Option 
> Click On Import or Export Preferences
> Give File Path
> Click On Save Button for Export and Open Button For Import 

**Expected result:**
It can be able to import or export the file and give the understandable error message  

**Screenshots**
**Export Image;**
<img width="664" alt="Export Error" src="https://user-images.githubusercontent.com/73606257/117552752-cb5db180-b066-11eb-9bdd-1224712bdae5.PNG">
**Import Image:**
<img width="640" alt="Import Error" src="https://user-images.githubusercontent.com/73606257/117552768-db759100-b066-11eb-90a7-3d62be2dd6f5.PNG">

**Comment by mikeberger** [comment]
you tried to overwrite the program exe? the error is clear. the file save dialog is just asking you where to save the preferences file.
