### ISSUE TITLE
Irresponsible Button

### ISSUE THREAD

**Issue by Hamadullah3592** [mikeberger/borg_calendar#115]
**Description:**
Delete Only One Button Could Not Working and Not Give any response. 

**Steps to reproduce:**
> Double click on Calendar 
> Make New AAPT
> Click On Delete One Only Button

**Expected result:**
It Must be perform an action of delete and show the successful delete item message in Display.  

**Screenshots**
<img width="960" alt="Bug10" src="https://user-images.githubusercontent.com/73606257/117554055-a5d4a600-b06e-11eb-9081-a48b98e040bf.PNG">

**Comment by mikeberger** [comment]
the button deletes appointments that are selected in the appointment list on the right side (which is empty in your picture)

i will add a notification if no appointments are selected in the appointment list and the button is pressed
