### ISSUE TITLE
Same functionality button

### ISSUE THREAD

**Issue by muhammaduzair866** [mikeberger/borg_calendar#118]
Description
Both Button have same functionality done and delete both remove entity

Steps to reproduce
Click on to do list
write to do list
then delete and done

Expected result
done means it don't delete 
delete means delete

Actual result
bot delete and done button have same result delete

Screenshot
![BUg-2(delete buttoh)](https://user-images.githubusercontent.com/81010115/117566904-b9b1f380-b0d2-11eb-9527-1d960db701bd.PNG)

**Comment by mikeberger** [comment]
as per the help:

The Done (No Delete) menu option, removes the appointment from the To Do list, but leaves it on the calendar. The Done (Delete) option removes it from the calendar also (unless the todo has more repeats, in which case the next occurrence is shown on the to do list).
