### ISSUE TITLE
Unnecessary buttons 

### ISSUE THREAD

**Issue by muhammaduzair866** [mikeberger/borg_calendar#119]
Description
in project tab then task if we close the task it closed and then we it also close

Steps to reproduce
Click project tab
Click task
then close and delete

Expected result
task is close when we click close button

Actual result
we have close and delete button both have same functionality 

Screenshot
![Bug-3(close-delete same)](https://user-images.githubusercontent.com/81010115/117567162-3c877e00-b0d4-11eb-81d0-823970195d42.PNG)

**Comment by mikeberger** [comment]
the close button does not delete the task. it changes the status to closed. if you change the status filter, you can see closed tasks.
