### ISSUE TITLE
Sync functionality is not working 

### ISSUE THREAD

**Issue by muhammaduzair866** [mikeberger/borg_calendar#120]
Description
it generates error when I was clicking sync tab 

Steps to reproduce
click on sync tab

Expected result
sync tab perform perfectly 

Actual result
erroer has been generated when i was clicking sync tab
![bug-4(sync)](https://user-images.githubusercontent.com/81010115/117567228-b4ee3f00-b0d4-11eb-86dc-b80099ccdc5c.PNG)

Screenshot

**Comment by mikeberger** [comment]
the message is clear. you cannot sync with a caldav server unless you set the proper options - like server address, name, password, etc....
