### ISSUE TITLE
Clone Error

### ISSUE THREAD

**Issue by muhammaduzair866** [mikeberger/borg_calendar#121]
Description
not more then two clone has been created

Steps to reproduce
Click on task
add task 
then create clone

Expected result
clone has been created when needed

Actual result
only two clone is created not more then that
![Bug-5(clone error )](https://user-images.githubusercontent.com/81010115/117567674-8c674480-b0d6-11eb-9d2d-85dc9cbc3239.PNG)

Screenshot

**Comment by mikeberger** [comment]
the clone button creates a clone of the selected task. after creating a clone, if you select the task again and press clone, another clone is created. i don't see a problem
