### ISSUE TITLE
managing function of Caldav Sync setting is not created 

### ISSUE THREAD

**Issue by dani00001** [mikeberger/borg_calendar#122]
Description: The error message is not user friendly which is not defined anywhere and there is no shortcut button to resolve the problem at a click. it's just show written error but solution not there on that tab lcal and mention the setting control just generate error of Caldav sync and managing function is not given.
Step to Reproduce:
1) Click on Ical button on navigation bar
2) Click on CADLAV button
3) Click on sync CADLAV

Expected Result:
When i go on caldav setting then it require to resolve the problem with help of managing and controlling function of caldav sync. 
Actual Result:
when i go on caldav setting is generating error and not giving to managing and controlling  function in caldav sync setting.
Screenshot:
![bug4](https://user-images.githubusercontent.com/83835442/117566905-bfa7d480-b0d2-11eb-9eb3-d60d6911af0b.png)

**Comment by mikeberger** [comment]
the message is clear. you cannot sync with a caldav server unless you set the proper options - like server address, name, password, etc....
adding a mechanism to have error popups redirect to the settings is not worth the effort. it takes 2 mouse clicks to open the settings.
