### ISSUE TITLE
Not Responding send Reminder Email

### ISSUE THREAD

**Issue by dani00001** [mikeberger/borg_calendar#125]
Description: :  Send Reminder Email button is not working when clicked and not perform any action or message generate.

Step to Reproduce:
1) Click calendar  
2) Make new APPT 
3) Click on Send reminder email button

Expected Result: The button requires to take an Email Id to send a reminder for the tasks. 

Actual Result:
No Action performing Send Reminder email button and this button is nothing do.

Screenshot:
![bug 2-3](https://user-images.githubusercontent.com/83835442/117569746-a017a880-b0e0-11eb-9127-52f21cbfde29.png)

**Comment by mikeberger** [comment]
if you have set up the email options, an email will be sent. it does not prompt for an email id
