### ISSUE TITLE
Not Correctly Use of ENTER button.

### ISSUE THREAD

**Issue by dani00001** [mikeberger/borg_calendar#126]
Description: : when clicked on enter button for more than one time, it starts moving on the existing check list.

Step to Reproduce:
1) Click on checklist
2) Press ENTER for Add check List Detail

Expected Result: 
It requires jump to a new line when contains a null value upon the click ,if no null value then add check list detail.

Actual Result:
It's just moving on existing checklist and not add check list detail when clicked on enter,

Screenshot:
![bug5](https://user-images.githubusercontent.com/83835442/117569782-d1907400-b0e0-11eb-901b-45d8149ed8e5.png)

**Comment by mikeberger** [comment]
it is just performing the default action on a JTable when enter is pressed.
no additional functionality was intended.
