### ISSUE TITLE
Irresponsive button

### ISSUE THREAD

**Issue by Anees-UrRehman** [mikeberger/borg_calendar#127]
Description: : when clicked on enter button for more than one time, it starts moving on the existing check list.

Step to Reproduce:

Click on checklist
Press ENTER for Add check List Detail
Expected Result:
It requires jump to a new line when contains a null value upon the click ,if no null value then add check list detail.

Actual Result:
It's just moving on existing checklist and not add check list detail when clicked on enter,

Screenshot:
![BUG2](https://user-images.githubusercontent.com/83958239/117704521-c8a2af80-b17f-11eb-8c22-aae9842b4dbf.PNG)

**Comment by mikeberger** [comment]
it is just performing the default action on a JTable when enter is pressed.
no additional functionality was intended.
