### ISSUE TITLE
Irresponsive button

### ISSUE THREAD

**Issue by Anees-UrRehman** [mikeberger/borg_calendar#128]
Description: : Send Reminder Email button is not working when clicked and not perform any action or message generate.

Step to Reproduce:

Click calendar
Make new APPT
Click on Send reminder email button
Expected Result: The button requires to take an Email Id to send a reminder for the tasks.

Actual Result:
No Action performing Send Reminder email button and this button is nothing do.

Screenshot:
![bug 5](https://user-images.githubusercontent.com/83958239/117704703-03a4e300-b180-11eb-8e41-ca0e8fc8159e.PNG)

**Comment by mikeberger** [comment]
if you have set up the email options, an email will be sent. it does not prompt for an email id
