### ISSUE TITLE
CALDEV SYNC not working

### ISSUE THREAD

**Issue by Anees-UrRehman** [mikeberger/borg_calendar#130]
Description:
it generates error when I was clicking sync tab

Steps to reproduce:
click on caldev sync tab

Expected result:
caldev sync tab should be executed perfectly

Actual result:
![bug 1](https://user-images.githubusercontent.com/83958239/117705598-15d35100-b181-11eb-86d7-7193652c80ac.PNG)

Gives error on sync button

**Comment by mikeberger** [comment]
the message is clear. you cannot sync with a caldav server unless you set the proper options - like server address, name, password, etc....
