### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by andrecc-7** [mikeberger/borg_calendar#136]
I think this app is neat, full of features, a lot I didn't explore yet. I have some suggestions on the looks:

- The calendar table could use less borders or different border width; for example the border separating the header from the days of the week could be thicker. The day ("monday", thursday", ...) might not need borders, but that would be to try and see how it looks.
- More consistent colors of the UI, since the focus is on the calendar all the UI should share a color scheme of dark or light tones, I don't know if the UI elements colors are customizable, but if they are, allowing users to change them would be cool.
- Update icons resolution and simplify them so they can all be the same color, a light or dark color, in this case github is a good example, all icons are grey in the dark blueish background.

An example that is not using CSS as a looks boost is https://imageglass.org/.

I prefer features over looks, but looks are good additional features.

**Comment by mikeberger** [comment]
All of the UI elements, except for the icons and calendar views are themable by changing the Java look and feel via an option on the appearance options tab. There should be 7 or 8 look and feels available by default - but no good dark ones.

The icons are from an ugly icon set that was the only one freely available in 2001. They were ugly then and have always needed updating.

Given the available technology 20 years ago, the calendar views had to be custom coded - i.e. calculate coordinates, draw line, move cursor, draw box, draw text, detect mouse position, etc... This means that they are not controlled by the Java look and feel. There is an options tab called User Color Scheme that allows you to customize the colors in the calendar views and save sets of color choices as "themes"

I have been considering packaging a dark look and feel from here: https://www.formdev.com/flatlaf/

I will post a picture of this in another comment....

**Comment by mikeberger** [comment]
In the picture below, the options window is using the dark theme - no coding needed. I customized the calendar view colors from the options window to match the theme. 

the icons are still the ugly set and do not match the dark theme. I'd have to get a new icon set.



![image](https://user-images.githubusercontent.com/6563665/125478991-9524c726-7a30-4c55-be83-523ba35ec9e8.png)

**Comment by andrecc-7** [comment]
Oh! I didn't notice it. I prefer the dark look, thanks.
