### ISSUE TITLE
[ICS Import] Using a category name > 15 chars results in SQL errors, and noting an unsuccessful import as a successful one

### ISSUE THREAD

**Issue by turner1991** [mikeberger/borg_calendar#14]
When editing an ICS file generated by BORGCalendar, you should avoid modifying the **categories** list such that a particular item is longer than 15 characters. Importing such a file will cause an SQL error to throw on that entry, which is expected. However, the import operation will finish by saying that the event has been imported, even though the event does not exist in the calendar (because of the error during import).

This issue can arise in situations where a user modifies an entry or batch of entries in an ICS file to change the category name before importing back into an installation of BORGCalendar (for example, sharing an itinerary with someone, on which the recipient performs a 'find and replace all' to try and use a category name they are used to seeing in some other calendar application).

#### Environment And Setup:
**Hardware:** MacBook 2014 15" Retina
**OS:** OS X 10.10, Windows 8.1 (6.3.9600)
**BORGCalendar Version:** 1.8.1 (on both OS X and Win8.1)

Consider the following ICS file contents:
——
BEGIN:VCALENDAR
PRODID:BORG Calendar
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20150121T213347Z
UID:1@BORGA-1421869872942
CREATED:20150121T213315Z
LAST-MODIFIED:20150121T213342Z
SUMMARY:Category name is too long.
DESCRIPTION:Category name is too long.
DTSTART;VALUE=DATE-TIME:20150130T155500Z
DTEND;VALUE=DATE-TIME:20150130T193500Z
CATEGORIES:IsThisTheRealLifeIsThisJustFantasyCaughtInALandslideNoEscapeFromReality
END:VEVENT
END:VCALENDAR
——
#### Reproduction:
1. Begin with any calendar (entries currently in the calendar does not appear to affect it)
2. Import the *.ICS File above via "Ical > Import"
3. You will be presented with a SQL error similar to the following:

*org.h2.jdbc.JdbcSQLException: Value too long for column "CATEGORY VARCHAR(15) DEFAULT NULL": "'IsThisTheRealLifeIsThisJustFantasyCaughtInALandslideNoEscapeFromReality' (71)"; SQL statement:
INSERT INTO appointments (appt_date, appt_num, duration, text, skip_list, next_todo, vacation, holiday, private, times, frequency, todo, color, rpt, category, reminders, untimed, encrypted, repeat_until, priority, create_time, lastmod, uid ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-173]*
4. Hit "OK“.
5. You will be informed that the entry imported successfully, but the entry will not be visible (The entry corresponds to 30 Jan 2015 in this example):
*Imported: 1
Skipped: 0
Duplicates: 0*

#### Possible Solutions:
- Mark this entry as skipped in the results window, or under some kind of error summary
- Perhaps gracefully fall back on a default category and import the event anyway. When parsing an ICS file, if the category is found to be too long, inform the user that the category for event X will be changed due to the underlying limitation. This allows the application to still import the event as completely as possible, which is (in my opinion) better than nothing.
- inform the users about the specific entries that had issues and did not import successfully. Perhaps offering them a list of names or ids so that they can refer to the imported file and manually move these entries over under a category they like that fits the database requirements.

**Comment by mikeberger** [comment]
good catch. the scenario of exporting, modifying, and importing a borg ICS file is not realistic. However, a truly ugly problem occurs if someone simply creates a long category name in another calendar (i.e. thunderbird, outlook, owncloud, etc...) and then tries to import or do a caldav sync with Borg. The SQL error will continue to occur on every caldav sync after that.
