### ISSUE TITLE
Sync the address book with CardDav

### ISSUE THREAD

**Issue by mikeberger** [mikeberger/borg_calendar#140]

**Comment by ecxod** [comment]
In advance, to import addresses from carddav, can you please show the XML schema?

**Comment by mikeberger** [comment]
Carddav contacts have different fields than my addressbook. I'd have to add the missing fields before it is usable. Otherwise, any import would drop some of the data. 

If I implement this, there would be an import in VCard (vcf) format, not XML.

The third party iCal library that I use is not fully functional for CardDAV. I'm still looking into how feasible this is.

**Comment by ecxod** [comment]
I would like Borg to store everything in Caldav/Cardav. The CardavCaldav server should be the main storage location, locally on any disk should not be anything.
Firstly to have the same data set with other devices or potentially other programs. 
Secondly, because it can be a real disaster if you ever have a broken hard drive. This has happened to me several times. That's why I never save anything that is not at least Raid1.

By the way: I'd like to have a git plugin that puts my commits into the caldav calendar.

**Comment by mikeberger** [comment]
In the Ical Options, you can set Borg to store any number of years of appointments to caldav instead of the default 2. This will put all data into caldav.
If you lose the Borg database and run a sync, Borg will reload all of its data from Caldav. Of course, all non caldav data, like memos, projects, checklists, is lost. Also, any Borg appointment data that does not get stored in the caldav model will get lost.
This is how most desktop caldav clients work. They keep a local data store for the caldav calendar without telling you. I assume that some keep extra data that is not in caldav.

I used to keep my borg db folder on dropbox. Now I sync to google drive. It doesn't get lost. I can get prior versions from google drive if the latest is corrupted. 

My Borg database contains 7000 appointments going back 31 years. This is too many to put on a cloud-based caldav server. It will not perform. I currently have baikal on a raspberry pi as of a few days ago. The caldav data can get corrupt just as easily as Borg. I choose to backup Borg as the master data store and do not need to backup caldav.

**Comment by mikeberger** [comment]
FYI - adding carddav is blocked by 2 issues. First, the carddav library that I rely on is incomplete. Second, I'd have to write a new address book from scratch. My current address records and UI can't handle anything close to what carddav allows. Since users might be using the current implementation, I'd wind up with 2 address different books.

**Comment by ecxod** [comment]
Please don't give up. The topic is very important.
We need only the syncronisationsfunktion. I will look around also. For PHP I have found a library. I have to have a look at the projects that can do this and what dependencies they use.

**Comment by mikeberger** [comment]
Carddav will only be partially supported in the next release. Borg will support import only - from a file or Carddav server. 

Contacts will be loaded into the existing address fields. No new fields are added.
