### ISSUE TITLE
Hidden icon shows previous date

### ISSUE THREAD

**Issue by s25765** [mikeberger/borg_calendar#145]
I put my computer to sleep on NOV 3rd, then went to bed.
Next morning, the 4th, when I woke up my computer, the mini icon in the task bar (click show hidden icons) still shows '3'.
It should show '4'.

**Comment by s25765** [comment]
I really like your program! It allows to me to use without internet connection or when I travel in a country where access to calendar server is blocked.

**Comment by mikeberger** [comment]
As a workaround, you can open the options window and press apply. It should force the date to update.

Make sure you backup (export) your data every so often if you are leaving the program running while sleeping the computer.

**Comment by s25765** [comment]
Thanks!
