### ISSUE TITLE
(question) changing colors of multiple events

### ISSUE THREAD

**Issue by TMS-Namespace** [mikeberger/borg_calendar#149]
Hi,

I used to have multiple calendars for different courses I have, so that I can give each a different color, however this is not available in BORG.

It seems that this is replaced by categories in BORG,  but there is no option to give category a color.

In search window, by selecting multiple events, color can't be edited either. Only, assigning a category is possible.

Then I noticed that you allow to execute SQL from BORG, but I found no reference for your data base structure.

So i decided to connect to H2 database by some DB browser, but it is protected by a password :(

So by this, all pathes are closed...

Can you please advice how I can overcome this to achive the goal I am looking for?

**Comment by mikeberger** [comment]
I've been thinking of doing something to add colors to categories or maybe have the 5 built-in colors become categories. I can also allow the colors to be set for multiple events from the search list. 

The database creation SQL is here: https://github.com/mikeberger/borg_calendar/blob/master/BORGCalendar/model/src/main/resources/borg_hsqldb.sql

The db login is "sa" and there is no password. The jdbc URL can be found under Help->Database Information. 

Example using the H2 console:
![Screenshot 2022-01-14 194425](https://user-images.githubusercontent.com/6563665/149607153-a7449023-a6e9-4034-a638-805bba704635.jpg)

**Comment by mikeberger** [comment]
code was committed to allow changing colors of multiple events from the search results.
