### ISSUE TITLE
Allowing an empty First and Last name entry into the address book by using XML imports

### ISSUE THREAD

**Issue by monasar** [mikeberger/borg_calendar#15]
##### Problem description:
An empty first or last name field can be added to the address book by importing an XML file with an empty FirstName/LastName XML tag. This does not satisfy the Function requirement 11, which states: 
  * REQ-11: In order for an entry to be added the First and Last Name have to be
inserted. Otherwise, a window pops up informing the user about this. All
the other fields are optional.

##### Environment and Setup: 
Hardware: Clevo Laptop, Desktop
OS: ArchLinux Kernal v.3.18.3, Windows 7
BORGCalendar Version: 1.8.1

##### How to reproduce: 
1. Start with an empty address book (for simplicity), create a new entry:
  * First Name: Steph
  * Last Name: Curry
  * All other fields can be empty
2. Export XML databases
3. Extract the exported zip file which contains ADDRESSES.XML
4. Modify ADDRESSES.XML by removing values of the FirstName tag and LastName tag 
  * from step 1, remove Steph from FirstName tag and remove Curry from LastName tag 
  * Check that it looks as the following:
```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
...
...
<FirstName></firstName>
<LastName></LastName>
...
```
5. Store the modification and import ADDRESSES.XML
6. Check the address book, you will find a empty entry for first and last name

##### Suggestion for Fix: 
  * Check that the XML FirstName and LastName tags have valid values when importing to an address book.
  * Display a window informing the user of any missing fields

**Comment by mikeberger** [comment]
fixed for first/last name and also invalid email addresses.
