### ISSUE TITLE
No information such as appointment(s) are displayed on a printed calendar when using GNU/Linux OS

### ISSUE THREAD

**Issue by saadnaji** [mikeberger/borg_calendar#16]
##### Problem description:
When attempting to print or export to a file of  a calendar using a Linux operating system, the output shows a grid of squares with corresponding numbers of the days in a month. However, no information such as added appointments are printed and nothing but the numbers themselves are seen. The first square may also starts with a random number rather than number 1 which refers to the first day of the month.

##### Environment and Setup: 
Hardware: Clevo Laptop, Desktop
JDK version: OpenJDK Java 7 development kit
Java version: 1.7.0_75
CUPS version: 2.0.1-1
OS:  Ubuntu 14.10 and ArchLinux  , Win 7
BORGCalendar Version: 1.8.1

##### How to reproduce the issue: 
1. Create an appointment(s) for any date of the currently selected month. 
2. Save the appointment, give it any name, ensure that it is not set to private.
3. Action -> Print.
4. Select one month to print, or more.
5. You can repeat step 1-4 but choose to tick Print To File instead of printing, and store the file.
6. The printed or the stored copy will contain only numbers, and will not show the added appointment(s) in step 1.

##### sample files:
From BORG calender view  : http://imgur.com/Q4i6rI7
Output on Linux : http://imgur.com/ZfEeIeC
Output on  Win7: http://imgur.com/AKENPTS
##### Suggestion for Fix: 
1. It should follow the printing output behavior similar of that Windows OS.
2. If unable to fix, disable the print function or warn the user of such behavior for the calendar when attempt to print on a Linux operating system.

**Comment by mikeberger** [comment]
This is a known issue with OpenJDK that has existed for many years. See the last item here: http://mbcsoft.com/joomla30/index.php/borg/12-linux-peculiarities

Users should use java from oracle if they want printing on linux. It works fine.

the only possible improvement is to detect that openjdk is running, and show a warning, but it is not worth the effort. To avoid a number of linux issues, the oracle version of java is recommended.
