### ISSUE TITLE
Missing .jar file(s) in source code

### ISSUE THREAD

**Issue by jelabarre59** [mikeberger/borg_calendar#162]
I did a git clone of the entire tree for Borg Calendar, and tried to run the linpackage.sh script for it (after changing "-t deb" to "-t rpm").  It's looking for the borg.jar file, but it doesn't appear to be anywhere in the repository.  

Now presumably the borg.jar file needs to be compiled, but I don't see how that gets done, and all the site tells me is how to download packages, and the readme only tells me how to make the installer.

(installing on Fedora, and I don't want to rely on Alien making a half-baked package).

**Comment by s25765** [comment]
FYI, after running 'mvn clean install' command, I saw borg.jar file on my computer:

C:\GitHub\borg_calendar\BORGCalendar>dir /s borg.jar
 Volume in drive C is OS
 Volume Serial Number is 9AB8-DF7A

 Directory of C:\GitHub\borg_calendar\BORGCalendar\install\target\installer

05/25/2022  08:33 AM           824,777 borg.jar
               1 File(s)        824,777 bytes

     Total Files Listed:
               1 File(s)        824,777 bytes
               0 Dir(s)  554,332,852,224 bytes free

**Comment by mikeberger** [comment]
To build you need a JDK version 17 or greater and apache maven. If you already have these, then "mvn clean install" will build borg.jar as stated in the comment above.

You can install maven and the jdk through the Fedora installer. I'm not sure if you will get the right versions though.

**Comment by RESDXChgfore9hing** [comment]
i think the new instructions are ok.
Maybe close this issue?

**Comment by mikeberger** [comment]
you are right. since the instructions are part of the github README and not a released file, I don't need to wait for a release to close this.
