### ISSUE TITLE
Few usage questions that are not answered in help

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [mikeberger/borg_calendar#166]
how to show private appointment,any way to switch mode?
how to make the popup window of todo(after pressed the frame icon thing) merge back into app main layout?

Also the text in help doesnt seems to obey the look and feel theme.
Try open the help section with,com.formdev.flatlaf.intellijthemes.materialthemuilite.FlatMaterialDarkerContrastIJTheme

**Comment by RESDXChgfore9hing** [comment]
oh wait i see the option to see private appointment.lol.sorry

**Comment by mikeberger** [comment]
The help window is created by the abandoned javahelp library. I'm glad it seems to be obeying the theme colors and default font as well as it does. I just provide it with HTML files that have no color or font settings.

For me, it changes the help font color perfectly and the font size changes correctly with the default font option. what issue are you seeing?

**Comment by RESDXChgfore9hing** [comment]
The html text is always black,which is weird with a dark contrast theme.
its like black on dark grey,but is not that important,can use mouse highlight to make the text white.

**Comment by RESDXChgfore9hing** [comment]
oh there is a dork function.
Hmmm... I think this is just a question thread thingy.
Its not a high priority thing,Just some UI questions and problem.
Can close anytime.

**Comment by mikeberger** [comment]
I get white text. This was fixed in the last release - 1.10.02. Are you on this release?

![image](https://user-images.githubusercontent.com/6563665/184788155-e8b5abfa-ca39-4cd4-ae26-f369a1b1cbee.png)

**Comment by RESDXChgfore9hing** [comment]
Oohhh, ok letme quickly update it thanks.

**Comment by RESDXChgfore9hing** [comment]
beautiful.
