### ISSUE TITLE
Quick question,wonder is it possible to temporarily disable the database,

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [mikeberger/borg_calendar#167]
I see the log it opens a port for the database,I wonder if its possible close the port and disconnect the database after collecting the todos etc,
and make sure the calendar is temporarily in a immutable* state.(for security reason?)

**Comment by RESDXChgfore9hing** [comment]
kinda like gui read only state.and anyone can try and touch it but it will not have the edited change.

**Comment by RESDXChgfore9hing** [comment]
the aim is to have a readonly database and the gui and no sockets exposed.
I see h2 db has a read only mode.maybe that's possible to be utilized.

for the socket exposed maybe we can instead,use a borg.lock file(when uses read only mode)?
just like those common documemnt editing software,eg libre office.

**Comment by RESDXChgfore9hing** [comment]
the main reason for no port exposed is for having absolute certainty that when you use borg in a public wi-fi port scanning attack just doesnt work.

**Comment by mikeberger** [comment]
There is no database port exposed. You can also disable Borg from opening its port in the options. However, this port should not be exposed to wifi - it does not need to be opened through your firewall. There is also no security risk exposed by this port. The only data sent over the port is the string "open" to tell a running Borg to open itself. No data can be read from the port.

Borg is not written to expect the DB to be open read only have all writes fail. It will error.

I still dont understand the use case. Are you trying to give another person read-only access? 
The database is just a local file to Borg. There is no running database server that can be accessed from outside Borg. The database is opened by Borg in embedded mode. It is just a file.

**Comment by RESDXChgfore9hing** [comment]
yeah you are right 

I see.hmmm.

Yeah,in the case of maybe showcase or something.
1 work around is to just point db to another place and then restart borg.

I think this issue is kinda resolved so will close the issue
