### ISSUE TITLE
Problem with installation in arch Linux

### ISSUE THREAD

**Issue by maricastanon** [mikeberger/borg_calendar#179]
### Discussed in https://github.com/mikeberger/borg_calendar/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **maricastanon** December 14, 2022</sup>
Good night,

I am trying to install borgcalendar in archlinux and I am not managing it. Could you help me?

I installed java.

```

$ archlinux-java status
Available Java environments:
  java-17-jdk
  java-19-jdk
  java-19-openjdk (default)
  java-8-openjdk

```

The sh file for installation has the following code:

`$JAVA_HOME/bin/jpackage -t deb --app-version 1.10.03 -n BorgCalendar --vendor MBCSoft -i target/installer --main-class net.sf.borg.control.Borg --main-jar borg.jar --linux-menu-group Borg --linux-shortcut

`
The first error said it was not finding the directory, than I:

`$ export JAVA_HOME=/usr/lib/jvm/default
`
The another error complained that was not compatible becuse was debian, then I installed

`$ sudo pacman -S dpkg`

And now the error when I run linpackage.sh is:

```
Bundler DEB Bundle skipped because of a configuration problem: The configured main jar does not exist borg.jar in the input directory
Advice to fix: The main jar must be specified relative to the input directory (not an absolute path), and must exist within that directory

```
Can any one help me to install this calendar please?
I am new to linux and it is the first time I try to open anything in JAVA.

I really want to install it because I want to try its features to see if they are a fit to my needs, and I intend on learning java to adapt it to my needs. 

Thank you very much in advance.

Best,
M</div>

**Comment by mikeberger** [comment]
Borg doesn't have an arch linux installer.

I set up an arch linux VM on virtualbox, but I get all kinds of errors just trying to use pacman. I've set up VMs for many distros in the past, and arch linux is the first distro to give me so much trouble. I'm not sure how much I want to fight with arch linux. 

I saw that there is a tool called debtap to install deb files on arch linux. I was hoping to try that, but I can't get pacman working. Perhaps you can try the debtap tool and see if it works with the BORG .deb file (the Debian installer).

**Comment by maricastanon** [comment]
Did you try installing debtap with -yay?
It is a package from AUR. that is why can't be installed with pacman.
First you have to instal yay from AUR,)
(and you have to install git with pacman for that, if you are using outside of root you always have t type "sudo pacman -S packagename")
so go to /usr/bin and do a git clone on yay's package (on AUR homepage you can find the link).
then you have to change the permission of the folder "yay" on the /usr/bin ( run sudo chmod -v 777 /usr/bin/yay)

now go to the yay folder (cd /usr/bin/yay)
and there you run "makepkg -si"
now yay is installed and you can use it to install packages from AUR by the name

command yay -S packagename to install

Does that help you?

Other option is to always do this git clone drama to install package per package, but yay is more practical.

Let me know if worked.
I will try it also tomorrow but the package I installed I think would do that. I am new to arch and linux in general, so don't know really what to do.

I really wantedthis calender because I am searching for a open source calendar to adapt as a project.

I do several tracking of habits, sleep, periode, medications, concentration, appointments etc and I would like to adapt a calender to track all those stuff from the same calendar xD FOr each tracking I use an app with calendar function and that is annoying, I would like to have all at the same place to be able to run some data analysis on my habits.

Do you think is possible with yours?

**Comment by mikeberger** [comment]
yay is not installed on the VM that I downloaded and the installer gives errors.

Try this file: https://github.com/mikeberger/borg_calendar/releases/download/v1.10.03/borg_without_jre.zip

unzip and then run: java -jar borg.jar in the borg folder. Use java >= 17.

This ZIP only contains BORG and does not include Java. I don't release this ZIP anymore because users always have so much trouble setting up Java themselves. 
The .exe and .deb installers set everything up including a private JRE and start menu items - but only for windows and linux distros that can handle deb files.

**Comment by maricastanon** [comment]
Good night Mark,

With this command I can yes launch the calendar.
Now... how do I manually set it up to run independently of the shell as a
desktop application?



Em qua., 14 de dez. de 2022 às 04:28, Mike Berger ***@***.***>
escreveu:

**Comment by mikeberger** [comment]
You can google how to set up a desktop launcher or menu launcher specific to your window manager.
Your window manager may have a graphical way of adding a menu item or desktop launcher.

I think that manually adding a .desktop file in the Desktop folder will work on almost all linux distros if your window manager supports desktop launchers.

Try creating a file called borg.desktop in your Desktop folder with contents like this

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=java
Icon[en_US]=java
Name[en_US]=Borg
Exec=/home/mbb/run_borg.sh
Name=Borg

Change the Exec variable to point to a shell script that does something like this:

cd your_borg_folder
$JAVA_HOME/bin/java -jar borg.jar

**Comment by mikeberger** [comment]
To resolve this issue, I'll release a simple portable version without an installer for linux distros that have .deb file compatibility issues.
https://github.com/mikeberger/borg_calendar/releases/download/v1.10.04/BorgCalendar_1.10.04.tar.gz
