### ISSUE TITLE
Blank Until field for appointment gives NullPointerException dialog

### ISSUE THREAD

**Issue by latagore** [mikeberger/borg_calendar#18]
**Version Used: 1.8.1**
### Procedure
1. Create a new appointment.
2. Set the recurrence to daily.
3. Select the radio button to "Until".
4. Click "Save and Close". Observe a dialog message which says "NullPointerException". Expect a better error message or different way of providing the information other than a dialog.

**Comment by mikeberger** [comment]
somehow the check for the missing until date was lost. adding it back.
