### ISSUE TITLE
how to detach ToDo panel in 1.10.03

### ISSUE THREAD

**Issue by DougBain** [mikeberger/borg_calendar#182]
Borg 1.10.03
I've recently installed 1.10.03 on a new computer.
Previously with earlier borgs I could pull off the ToDo pane and view it side by side with my month calendar. 
Now I can't: viewing ToDo replaces the month calendar.  
How can I detach the ToDo pane?

**Comment by mikeberger** [comment]
Undocking has always worked by pressing the square icon on a window tab. 

![image](https://user-images.githubusercontent.com/6563665/229504496-b784302d-a6d6-42f7-af9c-31b07b8c4e3d.png)

Do you not see the tabs at the top, below the button bar? The month view and todo views should always have separate tabs.

If you can't see the square undock icon or if pressing it doesn't work, try resizing the window first. You can also look in the log files for errors.
