### ISSUE TITLE
OK button not disabled for invalid input in Month View > "Go To" prompt

### ISSUE THREAD

**Issue by latagore** [mikeberger/borg_calendar#19]
**Version Used:** 1.8.1

### Procedure
1. Click the "Go To" in the top right of Month View.
2. Enter "Feb 21 2015" (instead of "Feb 21**,** 2015"; note the comma). Observe red text but you can still click the OK button. Expect that the OK button is disabled.

**Comment by mikeberger** [comment]
the Date chooser (except for the OK/Cancel buttons) is 3pp and does not report back when the date box turns red. I'll just have the OK button do nothing if the date is not valid.
