### ISSUE TITLE
Themes not working - (Windows 11)

### ISSUE THREAD

**Issue by Gold-nice** [mikeberger/borg_calendar#193]
Hello. I'm trying to update the theme in BORG Calender, and some do work, like the nimbus and metal themes. But when I try and switch to the Windows Look and Feel theme, I get this error message. 
"java.lang.IllegalAccessException: class net.sf.borg.ui.options.AppearanceOptionsPanel cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @23348b5d"
I don't understand why, so if anyone could explain, it would be appreciated. 
Thanks

**Comment by mikeberger** [comment]
Java changed at some point to add a feature called "modules" and this apparently caused a problem accessing the WindowsLookAndFeel. I can give a much more detailed explanation if you like.

You can work around this by ignoring the error and just restarting BORG with the WindowsLookandFeel selected. The code that sets the Look and Feel when the program starts actually works fine. The code that tries to change the Look and Feel when the program is running has 1 line different that no longer works with the WindowsLookAndFeel.

**Comment by Gold-nice** [comment]
I just tried the workaround, it worked. Thanks!
