### ISSUE TITLE
Today marker has weird category in To Do List

### ISSUE THREAD

**Issue by latagore** [mikeberger/borg_calendar#20]
**Version used:** 1.8.1

### Procedure
1. Open the To Do List view. Observe the ====== Today ====== entry and the corresponding "Today is" category. 
Expect that the "Today" entry does not appear *OR* the category is empty *OR* the category is corrected to its intended meaning.

**Comment by mikeberger** [comment]
Like many features, the today entry is the way it is because users wanted it that way - probably over 10 years ago. 

It has been the source of endless trouble. I will use this ticket as an excuse to remove it and highlight overdue todos in another way.
