### ISSUE TITLE
CANNOT INSTALL BORGCALENDAR IN KUMANDER OS 

### ISSUE THREAD

**Issue by dduran1210** [mikeberger/borg_calendar#210]
I get this error message installing the deb package:

Unable to install borgcalendar:  Error while installing package:  dpkg-deb –control subprocess returned error exit status 2

I tried updating and upgrading the os...but still get same error message.  How can i fix this ?

**Comment by mikeberger** [comment]
Try unpacking this file on your system: https://sourceforge.net/projects/borg-calendar/files/drops/BorgCalendar_1.10.04.tar.gz/download

You can just unpack in your home folder or anywhere you can write to.

Then run BorgCalendar/bin/BorgCalendar

There must be some incompatibility between dpkg on your system and the one I built the debian package on. Not sure how to debug that without more of an error message from dpkg.

**Comment by dduran1210** [comment]
well i unpacked it to /home  directory.....ran
BorgCalendar/bin/BorgCalendar   like you said  and  it works,

but it seems only if i go to /home and run it in the terminal there.  No
way to get the calendar icon on desktop to run it ?

I created a launcher on desktop and put the command in....but it pops up
the terminal.  close it and Borg shuts down.

better than nothing...but would like it to open with an icon on desktop.

**Comment by mikeberger** [comment]
When you create the launcher, do not check the box to launch in terminal.

**Comment by mikeberger** [comment]
To resolve this issue, I'll release the simple portable version without an installer for linux distros that have .deb file compatibility issues.
https://github.com/mikeberger/borg_calendar/releases/download/v1.10.04/BorgCalendar_1.10.04.tar.gz

**Comment by dduran1210** [comment]
It works!
