### ISSUE TITLE
Icon sizes are tiny in 4k resolution

### ISSUE THREAD

**Issue by gitthepie** [mikeberger/borg_calendar#217]
Is there any way to scale the application's icons to be larger in 4K resolution? I managed to increase the font sizes to compensate, but the icons (Month View, Week View, Day View, ... , Print, and Close All Tabs" are still puny.

**Comment by mikeberger** [comment]
The icons are 16x16. It is possible to scale the icons. I could imagine a new option to set the icon size.
Tracking down every icon in the code would be tedious.

I don't have a 4k monitor, so I wouldn't be able to see the results. I'd need someone to open all the screens and verify that they look ok. 

I don't know how good the icons will look scaled. Here are the month and print icons scaled to 32x32 on a 2k monitor:

![image](https://github.com/user-attachments/assets/9a002456-71aa-4d26-978f-b2e64c31d396)

**Comment by gitthepie** [comment]
That scaling idea sounds great! I attached a screenshot to show how the 32x32 scaled icon size (I used a browser zoom of 100% with your screenshot) looks next to my current unscaled icons. My 4k monitor is not huge, so I think a 48x48 and 64x64 option would be best, but even the 32x32 is already much easier to use.
![1](https://github.com/user-attachments/assets/98040b77-a86b-4b9e-bddd-01384e026c60)

**Comment by mikeberger** [comment]
I put both the windows and linux installers here: https://sourceforge.net/projects/borg-calendar/files/drops/

There is a new appearance option to change the icon size. You need to restart for icon size changes to take effect.

If it looks ok, I'll put out a new release. If there are problems, log them here.

**Comment by gitthepie** [comment]
I just tested your latest release. It looks awesome in 4K at 48x48 icon size! I've attached a screenshot to show the scale.

The only part of the UI that I haven't been able to scale is the list of fonts (you can see in the screenshot that the font sizes are too small to show in those tiny windows), but that's a minor problem compared to the icon sizes because I rarely change the font but I use the icons every day!
![1](https://github.com/user-attachments/assets/221ab54e-2b3b-4c44-845f-e807b031196e)

**Comment by mikeberger** [comment]
I'll switch to a better font chooser
