### ISSUE TITLE
Question: How to move/export all borg ui configurations&database

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [mikeberger/borg_calendar#219]
I bought a new computer and I wanted to move the database and all ui configurations to the new computer.
I tried export xml and import zip but seems to have no effect?

**Comment by mikeberger** [comment]
- export zip file
- transfer zip file to new computer
- install and run on new computer - database should now be empty
- import entire backup zipfile

If there is a problem, check the .borg.log and .borg.out files in your home directory (on windows this is %userprofile%) and post the errors here.

If there are no errors, this will import your data and your user color schemes. It will not set up your options, including choosing a look and feel and selecting the color scheme.

**Comment by hgftrdw45ud67is8o89** [comment]
oh sorry you are right,it imported successfully, a bit buggy probably fileio error.
but the ui configuration is not exported?my old device is dark theme and the new one seems unchanged.

**Comment by mikeberger** [comment]
You just need to change the Look and Feel in the options to a dark theme. If you created a custom dark theme under the user color scheme, you can switch to that in the options, as custom themes are imported along with the database. The latest release also has a BORG_DARK user color scheme included by default as well.

It is possible to transfer the options from one computer to another using the export and import preferences menu items under the options menu. This import/export is meant to backup your preferences on one machine only, not to transfer between machines. Many of the options are NOT compatible across machines, like file paths, window sizes, fonts. So, importing/exporting the options from one machine to another may break something, especially if the operating systems are different.

**Comment by hgftrdw45ud67is8o89** [comment]
i see huge thanks on info will close this issue
