### ISSUE TITLE
'System Beep' option for the Popup Reminder does not trigger a system beep.

### ISSUE THREAD

**Issue by Abasifreke** [mikeberger/borg_calendar#22]
<h5>Problem description:</h5>

The documented system feature for 'Popup Reminders' specifies that the user can edit preferences for the popup reminder sounds. This applies correctly for the 'Default' option and a sound is hear. However, if the user chooses the 'System Beep' option, the reminder doesn't trigger a system beep. Instead, no sound is heard. 

<b>Reference from SRS for BORG Calendar: 3.4.2 Stimulus/Response Sequences</b>
<b>8. </b> To select the alternative implementation (i.e. the separate popup window for each
reminder), <b>to change the sound that is played when a reminder pops up</b>, or to
 change the available popup times, select “Options” “Edit Preferences” and click
 on the “Popup Reminders” tab.

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>Can reproduce:</h5> Sometimes (most times).

<h5>How to reproduce the issue:</h5>

1. Launch the BORG Calendar application.
2. Click 'Options' on the menu bar.
3. Select 'Edit Preferences'. 
4. Select 'Popup Reminders'. 
5. Make sure the 'Enable Popup Reminders' Box is checked.
6. Select 'System Beep' as a reminder sound.
7. Click 'Apply' and then 'Dismiss'
8. Create an event (a Todo event is appropriate) and make sure that the 'Popup Reminder' is set for it
9. Wait for the popup reminder of the event you created to come up.
10. Listen for a sound and you should notice that system beep does not sound.

**Comment by mikeberger** [comment]
When System Beep is selected, java.awt.Toolkit.beep() is called. On windows, it will play one of the windows sounds (default beep?), but only if configured it in the windows sounds settings. Under linux, it can be more difficult to figure out as it requires a kernel module to work (a long story).

It works for me under windows 8.1, java 8. check your sound settings.
