### ISSUE TITLE
Problem with selection of date using mini calendar option

### ISSUE THREAD

**Issue by mbilal95** [mikeberger/borg_calendar#23]
<h5>Problem description:</h5>
When you try to assign a date to a task, if you use the mini Calendar to select the date and select
the February Month the application crashes, only the menu bar is functional the rest is not , this also occurs when adding a contact and select the person's birth date using the mini calendar and select the month February. 

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1.Select Address book.
2.Click "add new".
3.Enter "First name" and "Last name".
4.Go to "Birthday" and select the mini calendar icon beside the input textbox.
5.Once the mini calendar opens select February using the drop down list.
6.Notice that the application is stuck.

<h5>sample files:</h5>
![capture1](https://cloud.githubusercontent.com/assets/10716256/5963390/ca21013a-a7b9-11e4-8f33-c0aea627e556.PNG)
![capture3](https://cloud.githubusercontent.com/assets/10716256/5963391/ca255f82-a7b9-11e4-920a-729f4c6be5d9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10716256/5963392/ca26b6c0-a7b9-11e4-8e3f-159c36e914c9.PNG)

<h5>Alternate way to reproduce the issue:</h5>

1.Open Task.
2.Go to the "Tasks" tab ( which is right beside the "Projects" tab).
3.Click "Add" button.
4.Fill out the "Summary"
5.Select a "Start Date" (Suppose 1-Jan-2015)
6.Select a "Due Date" using the mini calender and select February using the drop down list in the mini calender.
7.Notice the application freezes again as described above.

<h5>sample files to alternate solution:</h5>
![killer1](https://cloud.githubusercontent.com/assets/10716256/5963696/71814eec-a7bc-11e4-80eb-f93a765f2825.PNG)
![killer2](https://cloud.githubusercontent.com/assets/10716256/5963697/7183686c-a7bc-11e4-86ac-a874d66efaa3.PNG)
![killer3](https://cloud.githubusercontent.com/assets/10716256/5963699/7185faaa-a7bc-11e4-9941-ce0ffbec8baa.PNG)
![killer4](https://cloud.githubusercontent.com/assets/10716256/5963698/7183bc04-a7bc-11e4-9a7e-7c4b67136e5a.PNG)

**Comment by mikeberger** [comment]
This is a bug in jcalendar version 1.3.2 (the calendar is 3pp). By coincidence, I upgraded to jcalendar 1.4 2 days ago and the bug appears to be fixed in that version. So it is already fixed in the master git branch.
