### ISSUE TITLE
Uninstaller does not kill the running process of BORG

### ISSUE THREAD

**Issue by gaglanicse03019** [mikeberger/borg_calendar#25]
**Description:**
------------------------------------------
If a session of BORG is running and the uninstaller is used, BORG will be uninstalled without prompting to kill the running process.

This can mean that BORG is uninstalled while there is still a running process. This may result in errors while using some functionality. For example, if the *Options > Reset Task States to Default* action is performed, a *java.io.FileNotFoundException* is thrown because the *model-1.8.1.jar* file no longer exists.

**Steps to reproduce:**
------------------------------------------
	1. Start BORG Calendar 1.8.1
	2. Use the BORG uninstaller
	3. Check the "Force the deletion of <installation dir>" option. The uninstall will complete without prompting to kill the running BORG process from Step 1

**Suggested Fix:**
------------------------------------------
When the uninstaller is used, the user should be notified that any running process of BORG should be killed prior to using the uninstaller.
		
**Environment:**
------------------------------------------
**Primary test environment:**
   *BORG - Berger-Organizer 1.8.1
   Build Time: 2015-01-17 14:51:28
   Java 1.7.0_65
   Ubuntu 14.04 LTS x86-64
   Macbook Pro 13" (Intel Core i5-2415M)*

**Secondary test environment:**
   *BORG - Berger-Organizer 1.8.1
   Build Time: 2015-01-17 14:51:28
   Java 1.7.0_65
   Windows 8 x86-64
   Lenovo Yoga 2 Pro (Intel Core i7-4510U)*

**Other info:**
------------------------------------------
Severity: Low

**Comment by mikeberger** [comment]
The installer that I use is IzPack, which doesn't provide a simple way to kill the running process or even tell the user to shut it down. I can't tell from the docs, but there may actually be an overly complex way to customize IzPack to do this. This scenario doesn't justify the effort.
