### ISSUE TITLE
Run SQL does not execute multiple SQL statements even though statements are semicolon (;) separated. Only the first statement is ever executed.

### ISSUE THREAD

**Issue by shawnmaharaj** [mikeberger/borg_calendar#27]
Sample statements
![sample queries](https://cloud.githubusercontent.com/assets/10761944/5967389/863b9d92-a7da-11e4-89f3-7eeb85436009.png)

Sample results
![resultset](https://cloud.githubusercontent.com/assets/10761944/5967402/9a88aa2e-a7da-11e4-9d68-a96ddc763cac.png)

Run SQL interprets both statements as shown by the table syntax error (the table “APPOINTMENTS” is spelled as “APPOINMENTS”). It doesn't make sense why if I were to correct the syntax error and run the two statements only the first result set is shown (select * from memos).

![incorrectsyntax](https://cloud.githubusercontent.com/assets/10761944/5967408/a75cd950-a7da-11e4-9067-7c313c56ef28.png)

Settings:
Linux, Intel i7-CPU, 8GB RAM, x86_64 architecture
borg 1.8.1

**Comment by mikeberger** [comment]
The Run SQL dialog is for simple debugging and for the rare case when I help a user fix DB problems , as it is not reasonable for most users to attach to the DB with some other 3pp tool. Any really advanced user that wants full SQL access to the DB can use any 3pp tool that connects to a JDBC database (and they do).

I'm not going to enhance the run SQL dialog beyond what it does. If someone really wants this capability (or if a college student needs something to code), they can find this ticket in the "wontfix" bucket and work on it.
