### ISSUE TITLE
Windows have no set minimum size.

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#28]
# Descprition:
BORG Calendar's windows can be re-sized to a minimal size that is small enough to visually lose the window; this is exacerbated if the system runs at higher resolutions.

This affects all windows that appear in the application.

# Steps to Reproduce:

    1. Start BORG Calendar 1.8.1
    2. Select any corner of the main window to re-size.
    3. Move cursor inwards towards the window and shrink window size until no longer possible

# Suggested Fix:
Set a minimum size for all windows, possibly dependent on the resolution.

# Environment:
**Primary Environment**
BORG - Berger-Organizer 1.8.1
Java 1.7.0_65
Windows 8.1 x86-64
Asus ROG G75VW (Intel Core i7-3630QM)

**Secondary Environment**
BORG - Berger-Organizer 1.8.1
Java 1.7.0_65
Red Hat Linux x86-64 VM
Asus ROG G75VW (Intel Core i7-3630QM)

# Other:
**Can reproduce:** Yes
**Severity:** Minimal

**Comment by mikeberger** [comment]
I don't plan to address this. It's another case of "just don't do that". If it happens accidentally, just resize the window bigger and move on.

If college students want to take a crack at this one and contribute it back via github - feel free.
