### ISSUE TITLE
Exporting out to XML then importing the exported file causes an SQL exception

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#30]
# Description:
Exporting out to XML then importing the exported file causes an SQL exception.
# Steps to Reproduce:
    1. Start BORG Calendar 1.8.1
    2. Click on Import/Export > Export XML
    3. Click on Import/Export > Import Entire Backup ZIP file and select the newly made file
# Suggested Fix:
Have the ability to merge tables rather than simply importing a new one with the same primary key (causing a violation in the schema).

# Environment:
BORG - Berger-Organizer 1.8.1
Java  1.8.0_31-b13
Windows XP Professional Service Pack 3
Dell Optiplex 8020 (Intel Core i7-4770, 512MB RAM)

# Other:
**Can reproduce:** Yes
**Severity:** Low

**Comment by mikeberger** [comment]
This would be an enhancement.
It is not a simple merge. It would need to be a full sync based on modification dates and some kind logic to determine if appointments with the same key are different versions of the same event or completely different items.

In any case, there is no user need for this. Backup is for full backup/restore. Actual users are not requesting this and are not using the XML for anything but full backup.
