### ISSUE TITLE
Print button does nothing when encountering an empty tab

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#31]
# Descprition:
With no tabs open, pressing the Print Button does nothing, or with a tab open (ie. Memos), and no items in that tab, pressing the Print Button does nothing.
# Steps to Reproduce:
    1. Start BORG Calendar 1.8.1
    2. Close all tabs
    3. Press the print button
# Suggested Fix:
Present an error message or have a popup dialog advising the user what to print
# Environment:
BORG - Berger-Organizer 1.8.1
Java  1.8.0_31-b13
Windows XP Professional Service Pack 3
Dell Optiplex 8020 (Intel Core i7-4770, 512MB RAM)
# Other:
**Can reproduce:** Yes
**Severity:** Minimal

**Comment by mikeberger** [comment]
not really a problem.

If someone wants to contribute this one - add a warning popup  saying that there is nothing to print.
