### ISSUE TITLE
Whitespace-only memo does not create a memo - or return an error.

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#32]
# Descprition:
Creating a new memo with whitespace characters only does not create a memo, but gives no error message
# Steps to Reproduce:
    1. Start BORG Calendar 1.8.1
    2. Click on memos
    3. Click new memo, and type only spaces.
# Suggested Fix:
Present an error message saying “INVALID MEMO”
# Environment:
BORG - Berger-Organizer 1.8.1
Java  1.8.0_31-b13
Windows XP Professional Service Pack 3
Dell Optiplex 8020 (Intel Core i7-4770, 512MB RAM)
# Other:
**Can reproduce:** Yes
**Severity:** Minimal

**Comment by mikeberger** [comment]
I'll leave this one for future student contributors.
