### ISSUE TITLE
Font sizes may cause overlap between input fields if too large

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#33]
# Descprition:
Font Sizes – possible to choose too large a font which causes letters and numbers to overlap in the views
# Steps to Reproduce:
    1. Start BORG Calendar 1.8.1
    2. Click on Options > Edit Preferences > Fonts
    3. Select a view, and scale the font size to 60
# Suggested Fix:
Provide dynamic font scaling, or limit the maximum font size such as to prevent letters overlapping.
# Environment:
BORG - Berger-Organizer 1.8.1
Java  1.8.0_31-b13
Windows XP Professional Service Pack 3
Dell Optiplex 8020 (Intel Core i7-4770, 512MB RAM)
# Other:
**Can reproduce:** Yes
**Severity:** Low

**Comment by mikeberger** [comment]
Trying to programmatically figure out when letters will overlap and then trying to scale the font would certainly introduce tons of bugs. 

The most acceptable solution would be for users to refrain from selecting absurd font sizes.
