### ISSUE TITLE
Uninstaller does not delete BORG files from file system (Windows specific).

### ISSUE THREAD

**Issue by pilayJorge** [mikeberger/borg_calendar#34]
# Descprition:
The uninstaller provided with BORG Calendar does not delete the BORG executable files from the file system. Moreover, BORG does not appear among programs to uninstall in the control panel. This is a Windows-specific issue as far as tested.

# Steps to Reproduce:
Uninstaller:
     1. Go to the folder where BORG files are stored (e.g. C:\Program Files\BORGCalendar)
     2. Go to Uninstaller directory
     3. Run uninstaller.jar

For Control Panel:
     1. Open Control Panel in Windows
     2. Open "Programs and Features" - BORG will not be listed among programs and features that can be uninstalled.

# Environment:
BORG - Berger-Organizer 1.8.1
Java 1.7.0_65
Windows 8.1 x86-64
Asus ROG G75VW (Intel Core i7-3630QM)

# Other:

**Can reproduce:** Yes
**Severity:** Low

**Comment by mikeberger** [comment]
This is a bug in the IzPack installer, not Borg. I don't plan to pursue this with the IzPack project. If they fix this in a future version, then I'll upgrade the installer to get the fix.
