### ISSUE TITLE
Blank Setup Shortcuts page during installation on Windows

### ISSUE THREAD

**Issue by arshad4313** [mikeberger/borg_calendar#36]
Description:
------------------
During the installation process on Windows, after the installation files are copied to the desired location on the *Installation* page, the page that follows is the *Setup Shortcuts* page. Once on that page, the user is given the options to create the desired shortcuts. Additionally, the user has the option to go to the previous page by pressing the *Previous* button. If this is done, the *Installation* step is automatically repeated again. If the *Next* button is then pressed, the user is taken back to the *Setup Shortcuts* page; however, unlike before, the page is now blank.

Note that this is not an issue on Linux. On Linux (Ubuntu), when the user returns to the *Setup Shortcuts* page, it is not blank; it has the same options available as when it was visited the first time.

Procedure to Reproduce Bug: 
------------------------------------
**Note**: When "(Step x of 7)" is mentioned below, it *does not* refer to the actual numbered steps, instead it is referring to the labels on each page in the BORG installer.

>	1. Start the BORG Calendar 1.8.1 installer (jar file or exe file) on a Windows 7 environment and proceed through the installer until the *Installation (Step 5 of 7)* page, then click *Next*
>	2. The next page shown will be the *Setup Shortcuts (Step 6 of 7)* page; notice that the page is populated with the necessary information/options
![image](https://cloud.githubusercontent.com/assets/10697341/5989332/5d2c824e-a952-11e4-81a9-ab0239b53d80.png)
>	3. On the *Setup Shortcuts (Step 6 of 7)* page, click the *Previous* button
>	4. The *Installation (Step 5 of 7)* page will be shown again
>	5. On the *Installation (Step 5 of 7)* page, press the *Next* button to go to the *Setup Shortcuts (Step 6 of 7)* page
>	6. Notice that the *Setup Shortcuts (Step 6 of 7)* page is now blank
![image](https://cloud.githubusercontent.com/assets/10697341/5989324/383ad152-a952-11e4-8cd1-d13629a16780.png)

Suggested Fix:
------------------------------------
On Windows, the *Setup Shortcuts (Step 6 of 7)* page should not be blank if the user decides to go to the previous page and visit the *Setup Shortcuts (Step 6 of 7)* page again.

Test Environments:
------------------------------------
**Primary test environment:**
	*BORG - Berger-Organizer 1.8.1
	Build Time: 2015-01-17 14:51:28
	Java 1.8.0_31
	Windows 7 x86-64
	Dell Optiplex 745 (Intel Core 2 Duo E6300)*

**Secondary test environment:**
	*BORG - Berger-Organizer 1.8.1
	Build Time: 2015-01-17 14:51:28
	Java 1.7.0_65
	Ubuntu 14.04 LTS x86-64
	Macbook Pro 13" (Intel Core i5-2415M)*

Metadata:
------------------------------------
**Severity**: Low
**Reproducible**: Yes (always)
**Affected platforms**: Windows 7, and likely Windows 8 (did not have Windows 8 available for testing)

**Comment by mikeberger** [comment]
This is a bug in the IzPack installer, not Borg. I don't plan to pursue this with the IzPack project. If they fix this in a future version, then I'll upgrade the installer to get the fix.
