### ISSUE TITLE
default LAF used on macs forces CTRL-based shortcuts over CMD-based ones

### ISSUE THREAD

**Issue by turner1991** [mikeberger/borg_calendar#37]
**Concern:**
Upon install on OSX, the application uses the **_com.jgoodies.looks.plastic.Plastic3DLookAndFeel**_ look and feel. This LAF is fine, but it doesn't support command (⌘) as the default modifier on mac environments -- users are forced to use CTRL, similar to windows environments.

Because the majority of applications running on Mac OS X tend to use the command key as their modifier (⌘+C to cut, ⌘+V to paste, etc), users might convince themselves that something is wrong, when in reality the third-party UI is just restricting them.

While this is not strictly an issue with BORG,  it might still be possible to ease users into some of the java-based oddities such as this.

**Proposals:**
- On install, check if the host operating system is some variant of OS X. If it is, set the default LAF to _com.apple.laf.AquaLookAndFeel_, or some other LAF bundled with the application that is able to use cmd-style keyboard shortcuts in the application.
- Alert them on first use to use CTRL, or when changing away from the Apple-supplied LAF in order to avoid confusion.

**Comment by mikeberger** [comment]
I don't have access to a Mac, so I would have no way to test this and would need someone to contribute this enhancement.

**Comment by mikeberger** [comment]
A change was made to default to the Java default L&F on Mac.
