### ISSUE TITLE
UI can sometimes fail to show ICS imported entries until restarting the application

### ISSUE THREAD

**Issue by turner1991** [mikeberger/borg_calendar#38]
When importing an ICS file of calendar entries in BORG Calendar, it is possible to work yourself into the situation where a restart of the application is required to see the newly added entries. All entries that import successfully (with respect to the summary window that pops up after the operation) are present in the database and interacting with these events works as expected.

##### Environment:
Operating System: OS X Yosemite (10.10), Windows 8.1 Professional
BORG Calendar Version: 1.8.1 for both operating systems

##### Reproduction:
1. Import the borg-38-init.ics file, if you do not have pre-existing calendar entries.
2. Start up BORG Calendar with some entries previously added.
3. Perform an ICS export to file of the current entries.
4. Immediately perform an ICS import of an *.ics file from the same directory (borg-38-import.ics).
5. The majority of the time, the entries will not show up until a program restart.

##### Notes:
- Importing the events works even though they don't show up (that is, importing the same *.ics file a second time will alert you to duplicates, as one would expect)
- Exporting the new calendar event set includes the events that do not visually appear on the calendar (meaning any syncing that happens after the fact considers the newly added data)

(( gist seems to be wonky for me tonight, so apologies in advance for needing to post the init and import ics files I've used here. ))

##### Starting Data (borg-38.ics):
------
BEGIN:VCALENDAR
PRODID:BORG Calendar
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20150201T003511Z
UID:1@BORGA-1422750594180
CREATED:20150201T002954Z
LAST-MODIFIED:20150201T002954Z
SUMMARY:test
DESCRIPTION:test
DTSTART;VALUE=DATE:20150121
DTEND;VALUE=DATE:20150122
CATEGORIES:black,ToDo
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20150201T003511Z
UID:3@BORGA-1422750674122
CREATED:20150201T003114Z
LAST-MODIFIED:20150201T003114Z
SUMMARY:Test event
DESCRIPTION:Test event using commas in the category name.
DTSTART;VALUE=DATE:20150130
DTEND;VALUE=DATE:20150131
CATEGORIES:black,lets\,use\,commas
END:VEVENT
END:VCALENDAR

------

##### Import Data (borg-38-import.ics):
------
BEGIN:VCALENDAR
PRODID:BORG Calendar
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20150121T213347Z
UID:1@BORGA-1421869872942
CREATED:20150121T213315Z
LAST-MODIFIED:20150121T213342Z
SUMMARY:This item doesn't appear in the UI until after a restart.
DESCRIPTION:"Test message."
DTSTART;VALUE=DATE-TIME:20150130T155500Z
DTEND;VALUE=DATE-TIME:20150130T193500Z
CATEGORIES:black,cat1\,cat2,black
END:VEVENT
END:VCALENDAR

------

**Comment by mikeberger** [comment]
You are importing an appointment with a category. By default, imported categories are not displayed. I guess it could be an enhancement to display new categories that do not exist in Borg until the import.
