### ISSUE TITLE
Consider disabling "Done" buttons on to-do list for the "== Today ==" entry

### ISSUE THREAD

**Issue by turner1991** [mikeberger/borg_calendar#39]
The Todo list allows users to interact with entries in two primary ways:
- adding new entries via the bottom section of the window
- editing and working with existing entries vie the right-click context menu for individual entries

There is a place-holder entry that marks the current date, whose to-do is "===== Today =====".

##### Concern:
The context menu for the placeholder is disabled, as one might expect since it's simply a placeholder and the application manages it for us. However, the two "Done" buttons underneath the list remain clickable despite not doing anything to the entry -- this could lead one to believe that they have the option to remove the place-holder if they wish, but are offered no way to do that from this view.

![image](https://cloud.githubusercontent.com/assets/10673298/5993774/170e1278-aa29-11e4-8140-da4cffdb8c7e.png)

##### Suggestions:
Perhaps one of the ideas below would help the application maintain uniform interaction:
- Disable the two "done" buttons for this entry, in order to keep a consistent appearance that this entry is not changeable in any way
- allow the user to remove the placeholder entry if they wish, by activating the buttons and allowing them to remove the item

**Comment by mikeberger** [comment]
already fixed in 1.8.2 due to ticket #20. Today marker has been removed.
