### ISSUE TITLE
Deleted contacts with birthdays do not update properly on current month view nor on the address book.

### ISSUE THREAD

**Issue by Abasifreke** [mikeberger/borg_calendar#44]
<h5>Problem description:</h5>

Right after deleting a contact with a birthday in the current month view from the address book, it makes no changes to the month view until an action (like scrolling to the next month and scrolling back to the original month) is done to the page of the month. Occasionally, the deleted contact does not also disappear from the address book i.e, it still shows on the address book even after deleting it.

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1. Launch BORG Calendar
2. Select Address book
3. If the address book already contains a contact which has a birthday in the month currently in the month view, then you can skip to step 11. Else, continue from step 4.
4. Click "add new"
5. Enter "First name" and "Last name"
6. Go to "Birthday" and select a date from the calendar in the month currently displayed in the month view.
7. Click "Save"
8. Close the address book
9. Check the month view to make sure the contact appears. If it does not, then scroll it to the next month and scroll back to the original month and the contact should now appear. 
10 Open the address book again.
11. Delete a contact that has a birthday in the month of the current month view.
12. Sometimes even after clicking "Ok" to delete the contact, it does not disappear from the address book and if you try re-deleting the same contact, you get a <b>java.lang.NullPointerException</b>.
13. Check the month view and you will notice that the deletion has not reflected on the month view.
14. Now scroll to the next month and then scroll back to the original month. The deleted contact finally disappears.
15. Relaunch the app, and the contact also finally disappears from the address book.

Note that the bug with the address book mostly happens especially after opening and using the calendar for a while (say an hour).

<h5>sample files:</h5>
The image shows two contacts that have been deleted but still show in the address book. They however do not appear anymore on the month view because I had scrolled to February and then back to January. Trying to delete the same contacts again, produced a <b>java.lang.NullPointerException</b>.
![capture1](https://cloud.githubusercontent.com/assets/10499046/5998031/98908c42-aa90-11e4-8725-8859f9473be0.JPG)

**Comment by mikeberger** [comment]
fixed by the changes to #35 and #41

**Comment by Abasifreke** [comment]
Ok. Thank you.
