### ISSUE TITLE
Documentation/Code Mismatch: Hitting F1 does not produce results specified by the Calendar's SRS

### ISSUE THREAD

**Issue by Abasifreke** [mikeberger/borg_calendar#45]
<h5>Problem description:</h5>

The Software Requirements Specification for the BORG calendar mentions that: 

1. SRS for BORG Calendar: 1.5 References - "The online help that can be accessed (after having installed and run the application) <b>by hitting F1</b> or using the Help menu." 

2. SRS for BORG Calendar: 2.6 User Documentation - "Included in the installation files is a user manual (which is not complete, nevertheless very useful) that can be accessed from within the program <b>by hitting F1</b> or using the Help menu."

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1. Launch the BORG Calendar application.
2. Hit f1.
3. Notice that no result is produced. Notice that neither the online help nor the user manual appears.

Note: Hitting F1 for the "Help" option is a very popular requirement by clients and is therefore available in lots of apps, so it would be unusual if this does not produce results for clients (especially those that have read the SRS for the Calendar).

**Comment by mikeberger** [comment]
This functionality was removed. I forget why. I would not be opposed to someone contributing this change if it can be added back without breaking anything.

Also - the SRS was written by a student as part of a college course. It is not up to date and was not used by this project.

**Comment by Abasifreke** [comment]
Ok. Thank you.
