### ISSUE TITLE
Appointments on 29th of February of Leap years repeat instead on the 28th in non-leap years.

### ISSUE THREAD

**Issue by Abasifreke** [mikeberger/borg_calendar#48]
<h5>Problem description:</h5>

When an appointment is added on the 29th of February in a leap year, then if it is set to repeat yearly, it ends up incorrectly repeating it on 28th of February in non-leap years. In contrast, the birthdays on the 29th of February in leap years correctly skip non-leap years and repeat on the 29th of February after the next 4 years. 

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1. Launch BORG Calendar.
2. Right-click on the 29th of a leap year (e.g. 2012)
3. Choose the "Add New" option. You'll see an "Appointment Editor" open up.
4. Under "Frequency", choose "yearly" and click on "Repeat Forever".
5. Make sure the "Show Repeat Number" is ticked. 
6. Now click "Save and Close"
7. The appointment appears on the leap year's 29th of February as it is supposed to.
8. However, when you check the following 3 years, the appointment appears in their 28th of Feb rather than skipping these years in the repetition.

<h5>Sample Files:</h5>
Date is set to 29th of February and the appointment is set to repeat every year.
![to-do made in a leap year for the 29th of february to be repeate yearly](https://cloud.githubusercontent.com/assets/10499046/6005526/135c6e30-aad9-11e4-9ae0-af9837cde7c9.JPG)

However, the appointment repeats on a 28th of February rather than skipping this non-leap year.
![29th repeated date is shifted to 28th on non-leap years](https://cloud.githubusercontent.com/assets/10499046/6005573/727a5dfa-aad9-11e4-827c-96cab167eff4.JPG)

**Comment by mikeberger** [comment]
not a problem. the appt should appear every year. the only issue is where. some calendars put it on March 1, but I prefer Feb 28. It may be an important todo, so we can't skip years.

**Comment by Abasifreke** [comment]
Ok. I understand. Thank you.
