### ISSUE TITLE
Documentation/Code Mismatch: "Red" bar at the top of the cell of a month or day does not appear.

### ISSUE THREAD

**Issue by Abasifreke** [mikeberger/borg_calendar#49]
<h5>Problem description:</h5>

The Software Requirements Specification for the BORG calendar mentions that:

SRS for BORG Calendar: 3.1.2 Stimulus/Response Sequences 6.-  "Alternatively, when in year view, place the mouse over a day’s number <b>(a red bar will appear)</b>and click. The day view of the specific day will appear.

SRS for BORG Calendar: 3.1.2 Stimulus/Response Sequences 7.-  " Alternatively, when in year view, place the mouse over a month’s name <b>(a red bar will appear)</b>. and click. The month view of the specific month will appear.

<h5>Environment and Setup:</h5>
Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1. Launch the BORG Calendar application.
2. You will notice that the month view is already open by default.
3. Click on "Actions" and click on the "Year View".
4. Now both the month and year views are docked.
5. Mouse over the top of any cell in both the year and month views and you will notice it has a "Black" bar rather than a "Red" bar. 
6. This is inconsistent with the Software Requirements Specification for BORG Calendar.

**Comment by mikeberger** [comment]
Please only add tickets on github if you are identifying a software bug. If the program is working ok, but doesn't match the SRS, then don't add a ticket. 
If this is for a college course, and you are testing the SRS, then perhaps there is another way for you to register this issue for the course?

In any case, the bar may have been red when the SRS was written. Now it is black.
