### ISSUE TITLE
Moving or Changing the Date of a repeating appointment 

### ISSUE THREAD

**Issue by mbilal95** [mikeberger/borg_calendar#50]
<h5>Problem description:</h5>
Making a repeating appointment and changing the date of any one repeating appointment will change all the appointments that were repeating. (For example an appointment that is repeated on weekly basis such as "Visit Grand Parents" and moving any one of the appointment to different day will move all of them to that same day) 

<b>Reference from SRS for BORG Calendar: 

REQ-7: The user cannot move (alter the date) of any occurrence of a series of
repeating appointments. If he/she tries to do so, a window will pop up
informing him/her that only the first occurrence of the series can be moved.
By doing that the whole series will be moved as one.

<h5>Environment and Setup:</h5>

Hardware(s): ASUS Laptop, Dell Laptop 
OS: Windows 8.1
Java version: 1.8.0_31
System type: 64-bit Operating System, x64-based processor
BORG Calendar Version: 1.8.1

<h5>How to reproduce the issue:</h5>

1. Make an appointment.
2. Select a frequency of recurrence of appointment (Weekly).
3. Select Repeat forever.
4. Go to Monthly view.
5. Drag that appointment and shift to another one (you can choose any appointment).
6. No warning or pop up box  shows up and it moves all the appointments to that day.
7. So the requirement from the specification is not satisfied. 

<h5>sample files:</h5>
![capture1](https://cloud.githubusercontent.com/assets/10716256/6006427/5e9b1c8c-aae0-11e4-90a7-222b4a3879a9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10716256/6006426/5e9a8f38-aae0-11e4-8db9-ab739b90f07f.PNG)

**Comment by mikeberger** [comment]
The SRS is not part of this project. Please do not write tickets based on the contents of the SRS.
