### ISSUE TITLE
The daysLeft(Date) method returns 0 for dates larger than INT_MAX days away

### ISSUE THREAD

**Issue by alicse03015** [mikeberger/borg_calendar#52]
## Description
In the TaskModel.java file there is a method: public static int daysLeft(Date dd) which should return the number of days before a given date. After testing I discovered that for inputs that are greater than INT_MAX days away from the current date, the method returns a value of 0.

## Steps to Reproduce
1. Create a date object 'd1' that is INT_MAX days away from the current date by:
```java
    Calendar c1 = new GregorianCalendar();
    c1.add(Calendar.DATE, Integer.MAX_VALUE); 
    d1 =  c1.getTime();
```
2. Create a date object 'd2' that is INT_MAX + 1 days away from the current date by:
```java
    Calendar c2 = new GregorianCalendar();
    c2.add(Calendar.DATE, Integer.MAX_VALUE + 1); 
    d2 =  c1.getTime();
```
3. Test daysLeft(Date dd) by passing in d1 as input, and observe that the value returned is INT_MAX (2147483647).
4. Test daysLeft(Date dd) by passing in d2 as input, and observe that the value returned is now 0.

## Suggested Fix
This issue most likely due to the fact that the method returns an integer value, and for days left that are larger than that value Java defaults the value to zero since it can not be stored in an int variable.  One potential fix is to make the daysLeft method return a long instead, so that a larger range of output values would be supported. However the probability that the user would need to compute the days between such a large gap is very small.

## System Configuration
**Primary Test environment**
BORG - Berger-Organizer 1.8.1
Last Commit: Feb 19, 2015
Java: 1.8.0_31
Windows 8.1 x64
AMD FX 8320 8-Core Processor 3.50GHz

**Secondary test environment:**
BORG - Berger-Organizer 1.8.1
Last Commit: Feb 19, 2015
Java 1.7.0_65
Mac OSX 10.9.5 (13F43)
Macbook Pro 13" (Intel Core i5-2415M)

## Metadata:
Severity: Low
Reproducible: Yes (always)

**Comment by mikeberger** [comment]
The fact that some code doesn't handle the case where you try to enter a task 5.8 million years in the future is not a bug.
