### ISSUE TITLE
re-opened problem with transferring calendar data

### ISSUE THREAD

**Issue by DougBain** [mikeberger/borg_calendar#58]
I'm transferring calendar data from a PC to an external HD and then plugging this into a laptop when abroad as my portable OS. I copy over borgdb.h2.db and borgdb.trace.db to keep the configuration in sync.

This mostly works fine, except that, with ToDo,  details I put in the note panel below the Subject in Appointment Text *don't* get transferred: the subject, yes; but notes, no. This is a real nuisance, when, for example, I'm abroad checking on my return flight and find the subject tells me I have a flight on such-and-such a date; but the flight and reservation number and time of arrival that were recorded in the notes on the PC haven't come across to the external HD.

**Comment by mikeberger** [comment]
This is strange as the database doesn't really have a separate field for the subject and notes. The subject and notes are only split up on the UI. I keep my database on dropbox and share it across 4 PCs. Most of my problems occur when I have a different Borg version on one machine or the preferences are different across machines.

On the machine with the problem, are the notes visible in the appointment editor but not on the calendar and todo list? If so, there is an option that controls this called "Truncate appointments in Month View" on the Appearance options tab. This option actually hides the notes on several screens.

If that's not the problem, perhaps you have different program versions on the different PCs?

**Comment by DougBain** [comment]
On 22/09/15 13:14, Mike Berger wrote:
>
> This is strange as the database doesn't really have a 
> separate field for the subject and notes. The subject and 
> notes are only split up on the UI. I keep my database on 
> dropbox and share it across 4 PCs. Most of my problems 
> occur when I have a different Borg version on one machine 
> or the preferences are different across machines.
>
> On the machine with the problem, are the notes visible in 
> the appointment editor but not on the calendar and todo 
> list? If so, there is an option that controls this called 
> "Truncate appointments in Month View" on the Appearance 
> options tab. This option actually hides the notes on 
> several screens.
>
> If that's not the problem, perhaps you have different 
> program versions on the different PCs?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikeberger/borg_calendar/issues/58#issuecomment-142270798>.
>
Thanks for your reply.

To the best of my knowledge the versions on the two machines 
are the same: 1.8.
I've tried disabling and enabling "Truncate appointments in 
Month View"; it has no visible effect either on Month View 
or the Appointments Editor.
On the affected machine there are no notes visible at all: 
the Appointments Editor has a single line available for 
Appointment Text, viz. the Subject; followed immediately by 
the Appointment Time - see Selection 1. On my other machine 
the subject line has a substantial space marked out for text 
- see Selection 2.

I haven't tried bringing back the calendar from the buggy 
machine to see whether the data is actually there but just 
not displayed, in case I lose the information in the good 
machine.

Doug

**Comment by mikeberger** [comment]
>the Appointment Time - see Selection 1. On my other machine
>the subject line has a substantial space marked out for text
>- see Selection 2.

did you attach images? I don't see any.

What is the screen resolution on the problem machine? 
If the appointment editor doesn't have enough vertical space to fit its components, it will drop some. I think the notes disappears first.

Can you maxmize the window? Can you detach the appt editor from the main window (press the square icon in the tab) and maximize it? Maybe that will get the notes to appear. 
If you have a low resolution screen, perhaps shrinking the font will allow more space for the UI widgets to appear as well.

**Comment by DougBain** [comment]
Thanks again for your very prompt reply - I'm puzzled you 
didn't find the attachments as they appear to have been sent 
normally.

Anyway, it turns out to be a lack of vertical space, as you 
suspected: on maximising the appt editor the notes appear OK.

Sorry I didn't think of that myself :(

Doug
