### ISSUE TITLE
No events visible after upgrade to 1.8.2

### ISSUE THREAD

**Issue by greyspammer** [mikeberger/borg_calendar#62]
I'm using BORG calendar against a MySQL database on a Linux host. After the upgrade to 1.8.2, the appointment overview for the month is empty. If I downgrade back to 1.8.1, I can see the appointments again. So the events aren't gone, they just don't show up.

If I manually synchronise against the DB, I get this error message repeatedly:
```
java.sql.SQLException: Column 'url' not found.
```

The release notes did not mention any necessary DB schema modifications. What did I miss?

Client: Windows, Oracle Java 1.8.0u66 with MySQL Connector/J 5.1.38
Server: Xubuntu 14.04.3 with MySQL 5.5.46

**Comment by mikeberger** [comment]
It looks like the popups that used to tell you how to upgrade MySQL have stopped appearing. You should see lots of upgrade SQL messages in the beginning of the log. they are in hsql dialect though, not mysql. I must admit that I last ran Mysql when 1.8.1 came out and I didn't even have a copy of mysql at all when 1.8.2 was released.

You can try the SQL below, but backup your db and/or export it first!!!!!

alter table appointments modify category varchar(255);
alter table tasks modify category varchar(255);
alter table projects modify category varchar(255);
alter table appointments add column url text;
alter table tasks add column create_time datetime default '1980-01-01 00:00:00' NOT NULL;
alter table tasks add column lastmod datetime default '1980-01-01 00:00:00' NOT NULL;
alter table tasks add column uid text;
update tasks set uid = CONCAT(tasknum,'@BORGT', RAND());
alter table tasks add column url text;
alter table subtasks add column create_time datetime default '1980-01-01 00:00:00' NOT NULL;
alter table subtasks add column lastmod datetime default '1980-01-01 00:00:00' NOT NULL;
alter table subtasks add column uid text;
update subtasks set uid = CONCAT(id,'@BORGS', RAND());
alter table subtasks add column url text;

CREATE TABLE syncmap (
 id integer NOT NULL,
 uid varchar(255), 
 objtype varchar(25) NOT NULL,
 `action` varchar(25) NOT NULL,
 PRIMARY KEY (id,objtype)
 );

**Comment by greyspammer** [comment]
Thanks. That seems to have worked. The syncmap table already existed, so the creation failed.

**Comment by borgs** [comment]
Hi Mike,

I don't understand why you are sending me these emails? Have you copied in
the wrong email address?

Regards,

Steve Borg (borgs1@gmail.com)
