### ISSUE TITLE
How to keep ToDo and calendar synchronized automatically?

### ISSUE THREAD

**Issue by DougBain** [mikeberger/borg_calendar#64]
I normally leave my PC running continuously, displaying the Month view and the ToDo list. I find that the date on the month view gets updated by the OS every day.
However ToDo is not updated and the only way I've found to do that is to Exit from Borg calendar and restart. It's a pain; so I'd be grateful if you could tell me how to set it to update automatically.
Many thanks,

Doug

**Comment by mikeberger** [comment]
I found a bug where if you close and reopen the todo window, it will stop updating when the calendar updates. The same is true for the search window. I will fix this.
So, if you have cases where entire todo rows are not properly being updated in the todo list when the calendar changes, this should fix it.

However, there really isn't anything on the todo list that reflects the current date except for the asterisk before overdue tasks. I can address this as well.

**Comment by DougBain** [comment]
On 10/01/16 17:54, Mike Berger wrote:
>
> I found a bug where if you close and reopen the todo 
> window, it will stop updating when the calendar updates. 
> The same is true for the search window. I will fix this.
> So, if you have cases where entire todo rows are not 
> properly being updated in the todo list when the calendar 
> changes, this should fix it.
>
> However, there really isn't anything on the todo list that 
> reflects the current date except for the asterisk before 
> overdue tasks. I can address this as well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikeberger/borg_calendar/issues/64#issuecomment-170374406>.
>
Thanks, Mike. In my situation it's the Today line that 
doesn't get updated, making it look as though I have more 
time available to do the things I ought to have done yesterday!

Doug

**Comment by mikeberger** [comment]
The Today line was removed about a year ago, so I was wondering what you were seeing.
I'll use this issue to fix the sync problems that I found in 1.8.2. I don't plan to go back and fix 1.8.1.
