### ISSUE TITLE
Translation Problem [Feature Request]

### ISSUE THREAD

**Issue by Hintsmth** [mikeberger/borg_calendar#72]
Hey there!
We want to help with translation into Russian. What should we do?

**Comment by mikeberger** [comment]
Hi,

There is an existing Russian translation that is out of date. you can change the locale in the BORG preferences to Russian and restart the program. Many items will now appear in Russian. The items that remain in English are the ones that need a translation added.

Updating the translations is different if you are a developer or not.

If you are a developer, you would check out the project from github and find the translations here: BORGCalendar/common/src/main/resources. Using a UI like eclipse, you can open the translations and just find the missing entries and edit them in Cyrillic directly. You would then create a pull request in github and I would merge it. Eclipse provides a UI that organizes and manages the translations, making it easy.

If you are not a developer, then the above probably made little sense and it is more painful. The translations are in the file common-1.8.3.jar in the lib folder where BORG is installed. You can open this jar (which is just a zip file) with software like 7-zip and edit the Russian translation, which is in borg_resources_ru.properties in the jar file. You would need to find the keys for the missing translations in the english version first - borg_resources.properties, and add the matching Russian translations in borg_resources_ru.properties. If you change the translation in the jar file and start BORG, you should see it.

The contents of borg_resources_ru.properties contains unicode escape sequences like this:

Edit = \u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C

So, you would need to use some kind of unicode editor.

Using an editor, it would look like this: 
Edit = Редактировать

You would email me the file and I would merge it into BORG.
