### ISSUE TITLE
Default location of config and data files

### ISSUE THREAD

**Issue by buhtz** [mikeberger/borg_calendar#74]
Where are the default locations of config and data files? How does BORG handle this on all systems?

I tried to find the correct place in the code but I am not familar with Java and Eclipse folder structure.

I also wasn't able to find a documentation about BORG on the website, in the repository and in the BORG GUI. If I missed it please point me to the right one.

**Comment by buhtz** [comment]
I found. The "Help" button is right aligned in the GUI and I overlooked it in that unusual swing gui.

The "Help" texts themselfs doesn't help because I can not do a search on them.

But the "Database" entry in the "Help" menu give a bit information. There is a path to the database.
Is this database the only file used by BORG? Or is there any other file I need to take care of?

**Comment by mikeberger** [comment]
The default BORG data store is an H2 database (www.h2database.com). The default location for the database is in %USERPROFILE%/.borg_db on windows and ~/.borg_db on linux.
There are options to use other JDBC database types, but I assume that they are not frequently used.

The config is stored as Java Preferences under the user node: net/sf/borg/common/util. On windows, this equates to HKEY_CURRENT_USER\Software\JavaSoft\Prefs\net\sf\borg\common\util in the registry. The default config values are in PrefName.java in the common project.

The SQL used to create the database is here: https://github.com/mikeberger/borg_calendar/blob/master/BORGCalendar/model/src/main/resources/borg_hsqldb.sql. This is only run to create the initial empty db.

The Java help system library that I use to build the help pages is old and buggy. The search function stopped working years ago and I had to disable it.

**Comment by buhtz** [comment]
Just to be sure that I understand you correct...

On Windows you store the configuration in the registry?
And where does the config goes on Linux and other plattforms?

**Comment by mikeberger** [comment]
I use the Java Preferences API: https://docs.oracle.com/javase/7/docs/api/java/util/prefs/Preferences.html

It is Java that actually stores the preferences somewhere for each OS. On windows, Java uses the registry. On linux, the preferences are stored in an XML file somewhere under ~/.java/.userPrefs
On MacOS, I am not sure. 
The actual OS-specific implementation is not a concern to the BORG code.

**Comment by buhtz** [comment]
I see. This make BORG plattform depended in my case.

I use different machines with different OSes (private, mobile, job, ...). For some applications (e.g. Firefox, Claws-Mail, vim) I sync the config files and other data. This work well in most cases. But I would need a bunch of files to do this.

For BORG I can not sync the Windows registry to a Debian system. So I can not use the same BORG data on both machines. I know this is kind of an exotic use case.

I am so sorry, but this makes BORG useless for me. It has a very nice approach and I see absolute no alternative to BORG. The other PIMs on the world have lot of other "problems".

**Comment by mikeberger** [comment]
My own setup has my BORG database on dropbox, so I can open BORG on any machine. the fact that the preferences are not synced is not a big issue for me.

I sync BORG's calendar with my own Owncloud server and use the caldav server in owncloud to make my calendar/tasks available on my phone and in caldav clients like thunderbird/lightning. There is also a web interface for owncloud.

to be honest, I could easily remove BORG from my setup and still use thunderbird as my thick client and the calendar clients on my phone and still be happy. 

Java swing clients are quite out of style. Most people will use whatever calendar/task apps come on their phones.

I guess we can close your issues.
