### ISSUE TITLE
limited length of string for a new contact

### ISSUE THREAD

**Issue by buhtz** [mikeberger/borg_calendar#75]
When I try to add a new contact I bump into a limit.

e. g. The nickname is limit to 25 characters. The street is limit to 40 characters.

Why is this limitation there? The answer would also answer the question how this could be solved.

I am using BORG 1.8.3 on Win10.

**Comment by mikeberger** [comment]
I switched the database to JDBC/SQL around 12 years ago. I don't remember if there was a valid reason for having a fixed length for all text fields in the database. I know that at my day job back then, we used Oracle and we always set limits to save disk space. If a limit wasn't set, the DB would use lots of space (i.e. 4096 chars per field). Back then, this may have been a big deal. 
These days, setting text limits for this kind of DB seems silly, I guess.
