### ISSUE TITLE
CalDAV Sync using SSL with LetsEncrypt gives CertificateException

### ISSUE THREAD

**Issue by tohuuuuu** [mikeberger/borg_calendar#84]
Hi, i've just tried to enable CalDAV sync with a server that's using a certificate issued by Let's Encrypt. 

I'm using borg calendar 1.8.3 on Win 10, Java 12.

Sync fails with the following error:

`net.fortuna.ical4j.connector.ObjectStoreException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Untrusted Server Certificate Chain`

Syncing works fine with other applications (Thunderbird, DavX5). I didn't try any Java-based application yet. SSL Server Test says that the server's ssl config is fine. Is there a way to make CalDAV sync with SSL and LetsEncrypt working?

**Comment by mikeberger** [comment]
Make sure you have checked the Borg option to allow self signed certificates. 

if that doesn't work, then I'd have to research if there are settings in the ical4j library that I use or options to pass to the JVM that would stop the JVM from complaining.

**Comment by tohuuuuu** [comment]
I've allowed self-signed certificates, but this doesn't change anything. But i've managed to get it running by importing the Let's Encrypt certificates manually from https://letsencrypt.org/certificates/ into the jre keystore. When syncing to baikal, i've got several NPE's, but after restarting borg, appointments and todos are visible in the repective tabs.

**Comment by ecxod** [comment]
I think this issue can be closed, I tested it and it works.
