### ISSUE TITLE
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by ecxod** [mikeberger/borg_calendar#85]
I can confirm that the program works perfectly with Baikal Server, (it would have been nice once could more then one account.
**carddav heavy missing.**

**After fresh install connection to MySQL not possible.** 
First comes the Failure : 

Das Datenbankverzeichnis ist gesetzt auf: jdbc:mysql://192.168.178.100:3306/borgCalender?user=borgCalender&password=borgCalender&autoReconnect=true
Wenn ein fehlerhaftes Datenbank-Verzeichnis den Fehler verursachte,
 bitte 'JA' wählen, um es zu ändern.

then again the input window an then nothing.
I just could uninstall the app. 

I have Java installed and the Mysql Java Driver last version.  (Build 1.8.0_231-b11)
Mysql Server 10.2.30-MariaDB-10.2.30+maria~stretch-log

**Comment by mikeberger** [comment]
Changes to Java have broken the way that Borg loads the mysql driver jar from the lib/ext folder. Java 11 also takes away the option to add the mysql driver to the JRE/lib/ext folder.

The best workaround would be to add the mysql jar to Borg's lib/ext folder and then run from the command line:
C:\Program Files\BORGCalendar>java -cp "borg.jar;lib/*;lib/ext/*" net.sf.borg.control.Borg

I also need to point out that I have not run with MySQL for as long as I can remember. I don't know if you will find other problems with MySQL.

**Comment by ecxod** [comment]
I would prefer to sync the great Tasks ToDos and so on via CALDAV. but prolly this is more complicated ...

**Comment by mikeberger** [comment]
Cleaning up old issues...

For this one, hopefully the Mysql workaround is good. I am not sure if I can package the Mysql driver due to licensing issues.

In the next release, sqlite will be added as a DB option. Mysql should still work, but is no longer tested.
