### ISSUE TITLE
Uninstalling is not uninstalling

### ISSUE THREAD

**Issue by ecxod** [mikeberger/borg_calendar#86]
after uninstalling a Window shows as if the files have been deleted, 
but after checking they are still here.

C:\Program Files\BORGCalendar\Uninstaller\uninstaller.jar
C:\Program Files\BORGCalendar\run_borg.sh
C:\Program Files\BORGCalendar\RELEASE_NOTES.txt
C:\Program Files\BORGCalendar\licenses\the mit license - license.txt
C:\Program Files\BORGCalendar\licenses\the bsd license - bsd-license.html
C:\Program Files\BORGCalendar\licenses\the apache software license, version 2.0 - license-2.0.txt
C:\Program Files\BORGCalendar\licenses\mpl 2.0 or epl 1.0 - license.html
C:\Program Files\BORGCalendar\licenses\mit license - mit-license.php.html
C:\Program Files\BORGCalendar\licenses\LICENSE.jnlf
C:\Program Files\BORGCalendar\licenses\LICENSE.ical4j
C:\Program Files\BORGCalendar\licenses\hsqldb license - hsqllicense.html
C:\Program Files\BORGCalendar\licenses\gplv2+ce - cddl+gpl_1_1.html
C:\Program Files\BORGCalendar\licenses\gnu lgpl (gnu lesser general public license), v2.1 or later - lgpl.html
C:\Program Files\BORGCalendar\licenses\gnu lgp (gnu general public license), v2 or later - lgpl.html
C:\Program Files\BORGCalendar\licenses\gnu lesser general public license - lgpl.txt
C:\Program Files\BORGCalendar\licenses\gnu general public license - version 2 - gpl-2.0.html
C:\Program Files\BORGCalendar\licenses\epl (eclipse public license), v1.0 or later - legal.html
C:\Program Files\BORGCalendar\licenses\eclipse public license 1.0 - epl-v10.html
C:\Program Files\BORGCalendar\licenses\common development and distribution license (cddl) v1.0 - cddlv1.0.html
C:\Program Files\BORGCalendar\licenses\cddl - cddl.txt.html
C:\Program Files\BORGCalendar\licenses\bsd license - bsd-license.php.html
C:\Program Files\BORGCalendar\licenses\BORGCalendar-THIRD-PARTY.txt
C:\Program Files\BORGCalendar\licenses\apache license, version 2.0 - license-2.0.txt
C:\Program Files\BORGCalendar\licenses\apache license, v2.0 or later - licenses.html
C:\Program Files\BORGCalendar\licenses\apache license - license-2.0.txt.html
C:\Program Files\BORGCalendar\lib\slf4j-api-1.6.6.jar
C:\Program Files\BORGCalendar\lib\model-1.8.3.jar
C:\Program Files\BORGCalendar\lib\mail-1.5.0-b01.jar
C:\Program Files\BORGCalendar\lib\looks-2.2.2.jar
C:\Program Files\BORGCalendar\lib\lombok-1.16.18.jar
C:\Program Files\BORGCalendar\lib\jcl-over-slf4j-1.7.4.jar
C:\Program Files\BORGCalendar\lib\jcalendar-1.4.jar
C:\Program Files\BORGCalendar\lib\javahelp-2.0.05.jar
C:\Program Files\BORGCalendar\lib\jackrabbit-webdav-2.7.1.jar
C:\Program Files\BORGCalendar\lib\ical4j-vcard-0.9.6.2.jar
C:\Program Files\BORGCalendar\lib\ical4j-connector-borg2.jar
C:\Program Files\BORGCalendar\lib\ical4j-1.0.5.2.jar
C:\Program Files\BORGCalendar\lib\hsqldb-1.8.0.10.jar
C:\Program Files\BORGCalendar\lib\h2-1.4.196.jar
C:\Program Files\BORGCalendar\lib\filedrop-1.1.jar
C:\Program Files\BORGCalendar\lib\ext\README.txt
C:\Program Files\BORGCalendar\lib\ext
C:\Program Files\BORGCalendar\lib\commons-net-3.6.jar
C:\Program Files\BORGCalendar\lib\commons-logging-1.1.3.jar
C:\Program Files\BORGCalendar\lib\commons-lang-2.6.jar
C:\Program Files\BORGCalendar\lib\commons-io-2.3.jar
C:\Program Files\BORGCalendar\lib\commons-httpclient-3.1.jar
C:\Program Files\BORGCalendar\lib\commons-codec-1.8.jar
C:\Program Files\BORGCalendar\lib\common-1.8.3.jar
C:\Program Files\BORGCalendar\lib\base64coder-2010-12-19.jar
C:\Program Files\BORGCalendar\lib\backport-util-concurrent-3.1.jar
C:\Program Files\BORGCalendar\lib\activation-1.1.jar
C:\Program Files\BORGCalendar\COPYING
C:\Program Files\BORGCalendar\borglicense.txt
C:\Program Files\BORGCalendar\borg.jar
C:\Program Files\BORGCalendar\borg.exe
C:\Program Files\BORGCalendar\.installationinformation
C:\Program Files\BORGCalendar

**Comment by ecxod** [comment]
I found a workaround. Just delete the folder in programs, and then look in the registry for Borg .
HKEY_USERS\ ....\Software\JavaSoft\Prefs\net\sf\borg\common
delete everything there ...

**Comment by mikeberger** [comment]
I have always used IzPack (http://izpack.org/) as my installer. It has always amazed me how it has the built in uninstall option that never manages to delete the files.  I was hoping that they would fix this, but they never have.
