### ISSUE TITLE
Handshake failure when setting up Caldav Sync

### ISSUE THREAD

**Issue by samir-s** [mikeberger/borg_calendar#88]
Hi,
I'm trying to set up caldav sync with a nextcloud server (LetsEncrypt on), but failed to log in.

Logs:

Jun 16, 2020 5:54:13 PM net.sf.borg.control.Borg processMessage
FINE: Got msg: log:SYNC: connect to https://subdomain.domain.tld
Jun 16, 2020 5:54:13 PM net.sf.borg.model.ical.CalDav connect
INFO: SYNC: connect to https://subdomain.domain.tld
Jun 16, 2020 5:54:13 PM net.sf.borg.common.Errmsg logError
SEVERE: net.fortuna.ical4j.connector.ObjectStoreException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Environment:
W10/Java 13.0.2/BORG 1.9.0.1

Step to reproduce:
1. CALDAV Server: subdomain.mynextcloud.tld
CALDAV User: john CALDAV Password: myPassword
CALDAV Calendar: BORG
Principal path: /remote.php/dav/principals/users/john/
Check use SSL & Allow Self-Signed SSL

As a side note, there is a lot of stuff to fill in the CALDAV config, I would suggest to only fill the complete CALDAV URL: https://subdomain.domain.tld/remote.php/dav/principals/users/joe/
and get rid of principals/user/base server and all, that's confusing in my opinion and not UX friendly.

**Comment by mikeberger** [comment]
Please check this issue: https://github.com/mikeberger/borg_calendar/issues/84 and see if that helps.

I use a third party CALDAV library that requires all of those separate configuration parameters and does not provide an API for getting them from a complete principal URL - logic which would differ for each caldav server type.

I used nextcloud years ago. I don't have my settings saved, but I think that your principal path should omit the /users/john (once you get past the SSL handshake). I also think my base path was /nextcloud (installation dependent), and my principal and user paths omitted the starting slash as well. All of these settings were "magic" needed to get the caldav library to work right.

**Comment by samir-s** [comment]
I've already seen this issue. Do I need to import the LE certificate into the jre keystore to make it work ? I don't know how to do that... Actually, I thought that checking self-signed certificate was to make it work out of the box.

**Comment by mikeberger** [comment]
It looks like I broke the self-signed certificate code with this change: https://github.com/mikeberger/borg_calendar/commit/6817ce6db13029bfcaddc2e6e3b816c27a3410ae#diff-1eeb8cdeb39b6ecfaa39f535403d1379


The code that I used (copied from somewhere) was not compatible with Java 10 and I broke it when migrating to Java 10. I will look into it.

**Comment by mikeberger** [comment]
I have a fix. You can replace the installer EXE in the windows installer ZIP with this one: https://github.com/mikeberger/borg_calendar/releases/download/1.9.0.1/borg_installer-1.9-sslfix.exe

I tested with nextcloud. Interestingly, for my nextcloud, the principal path had to be remote.php/dav/calendars and not remote.php/dav/principals.

**Comment by samir-s** [comment]
Tried to install the fix but get an error when installing:

com.izforge.izpack.api.exception.IzPackException: An error occured
in java.lang.Thread.run() at Thread.java:830
in com.izforge.izpack.installer.unpacker.UnpackerBase.run() at UnpackerBase.java:241
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:319
Caused by: java.lang.NullPointerException: null
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:299
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:475
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:528
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:627
in com.izforge.izpack.installer.unpacker.UnpackerBase.extract() at UnpackerBase.java:673
in com.izforge.izpack.installer.unpacker.LooseFileUnpacker.unpack() at LooseFileUnpacker.java:92
in java.io.File. () at File.java:359

**Comment by mikeberger** [comment]
The fix is not a full installer. Make sure that you unzip the normal windows installer and then run the sslfix installer from the folder where you unzipped the full installer.

![image](https://user-images.githubusercontent.com/6563665/92762591-bce8ba00-f360-11ea-91c0-b53337f0c6f8.png)

**Comment by samir-s** [comment]
That's exactly what I did: the problem still holds.

**Comment by mikeberger** [comment]
Just replace the following jar in the BORG lib folder: https://github.com/mikeberger/borg_calendar/releases/download/1.9.0.1/model-1.9.jar

**Comment by mikeberger** [comment]
closed with release 1.9.0.2.
