### ISSUE TITLE
LimitDocument values in AddressView.java are far too small

### ISSUE THREAD

**Issue by ArenT1981** [mikeberger/borg_calendar#89]
Hello

Great software! Thanks for all the hard work. Just one massive annoyance when I was using it. 

The constraints on the entry fields for new contacts (i.e names, and in particular, fields like "Street Address" are far far too low!). As in way off, IMO. 40 characters for the Street Address line is nothing.

Other limits are also far too low - only 25 characters? Some people have long names :-)

I presume this may also necessitate slightly increasing the column sizes in the underlying database model, but in 2020 diskspace is super cheap so I can hardly see it making any appreciable difference unless you're storing like a million records... 

I'd suggest 100 characters for all fields as a base minimum, with certain awkward fields like Street Address able to hold perhaps 200 (addresses in foreign countries can often involve a lot of characters).

If I feel like altering these values myself to something I consider more sensible (i.e. I'm inclined to make them about 4-5x their current size), do I need to modify anything else in the code to make it build, such as any database code?

Thanks.

**Comment by mikeberger** [comment]
Those field sizes were in the initial commit back in 2004. I have no memory of why they were chosen. I used to have code that synced borg with my Palm (https://www.gpsinformation.org/dale/Palm/iQue3600.htm). Maybe that had limits? That is also ancient history that is long forgotten.

If you want to change the sizes, you would change the AddressView, the 2 DB creation SQL files, and doDBUpgrades() in JdbcDB.java. doDBUpgrades() is used to alter column sizes in existing databases. If you are just making changes for yourself (i.e. not a pull request) and don't need to auto-upgrade an old database, you can skip doDBUpgrades().

**Comment by ArenT1981** [comment]
Thanks for the reply. I'll look into making the amendments.

I'm also trying to get BORG to work with my Nextcloud calendar without much success... 

I've tried dozens of combinations of values in all of the fields, but none ever seem to work. It logs in, and then it seems to find the principals, but then complains it can't find my calendar. Do you know what combination of values to use?

Here is my private calendar link (my username obfuscated):

`https://nc.nl.tab.digital/remote.php/dav/calendars/foo@bar.com/personal/`

Here is what Nextcloud reports as my "primary CalDAV address":

`https://nc.nl.tab.digital/remote.php/dav`

Alternatively, if you click on the "copy iOS/MacOS CalDAV address" link instead it gives:

`https://nc.nl.tab.digital/remote.php/dav/principals/users/foo@bar.com/`

And finally, suppose the name of my calendar is `MyCalendar`.

Trying these values:

![image](https://user-images.githubusercontent.com/45647975/87319312-5fcbb600-c521-11ea-9278-764f0e7c50e7.png)

Results in:

![image](https://user-images.githubusercontent.com/45647975/87319338-69551e00-c521-11ea-97ea-c1c1f30b12e3.png)

Even though the path seems to be exactly right... (Meanwhile if I remove the initial / from the Server Base Path field, it ends up freezing, trying to connect to https://nc.nl.tab.digitalremote.php/dav etc., i.e.. there is no directory separator between the hostname and remote.php. Removing "MyCalendar" so it just points at the directory also doesn't help.

Frustrating, because it feels like it is so "nearly" right, but I've been trying different values for about 2 hours now... :-)

**Comment by mikeberger** [comment]
Try base path = /
principal path = remote.php/dav/principals
user path = remote.php/dav/calendars
calendar = personal

if that doesn't work, try principal path = remote.php/dav/calendars

For some reason, the nextcloud version that I test with works only with "remote.php/dav/calendars" as both paths. I have no idea why. 

The third-party library that I use to talk to caldav requires these separate parameters. I wish there was a free third-party library that would just take the calendar url and auto-detect everything,  but I don't know of one.

**Comment by ArenT1981** [comment]
Thanks for the suggestions. No joy.

Like you, I have to set the principal path to `remote.php/dav/calendars`. Alternatively, `remote.php/dav/principals/users` also works in terms of logging in.

But then it just complains it cannot find the collection as per the above error message, regardless of whether I put `personal`, `personal/`, `personal/MyCalendar`, or `MyCalendar` in the CalDAV calendar setting.

What makes it more frustrating is that the error message complaining about not being able to find the calendar is pointing to exactly the right path, and I know it to be correct, because I setup DAV5x on my Android phone and it works perfectly...

Interestingly, the "auto" setup option in DAV5x failed. I had to set it up by choosing the "Login URL" option, where you specify the login URL, then your username and finally your password. The login URL had to be specified as:

`https://nc.nl.tab.digital/remote.php/dav/principals/users/`

Using `remote.php/dav/principals/users` in BORG as the principal path does indeed seem to be correct in terms of authenticating. It just can't find my calendar... Very strange. I don't get why it isn't working/can't find it.

![cal-settings-obfus](https://user-images.githubusercontent.com/45647975/87669721-6303b380-c766-11ea-8ea4-275aeb5e1581.png)

**Comment by ArenT1981** [comment]
In the meantime I can at least do a one-way sync by either just manually exporting then importing the ics file into BORG, or optionally share my calendar with a generated link and use that with the import URL option under BORG. Option 2 isn't great from a privacy point of view (not that there is likely to be much of interest in my calendar for anyone). 

For now I guess I'll just do manual export/import of an ical file, since I am mainly desktop orientated (I work remotely as a developer) so as long as I have everything in BORG I can use it as my main place of operation. Is a pity that I can't get full two-way to work though, but no deal-breaker.

---

Update. Looking in `~/.borg.out ` I see a few more lines of potential interest:

```
net.fortuna.ical4j.connector.ObjectStoreException: unable to get collection '/remote.php/dav/calendars/foo@bar.com/personal'
        at net.fortuna.ical4j.connector.dav.CalDavCalendarStore.getCollection(CalDavCalendarStore.java:162)
        at net.sf.borg.model.ical.CalDav.getCollection(CalDav.java:217)
        at net.sf.borg.model.ical.CalDav.checkRemoteSync(CalDav.java:448)
        at net.sf.borg.control.Borg$9.run(Borg.java:568)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: org.apache.jackrabbit.webdav.DavException: Service Unavailable
        at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseException(DavMethodBase.java:165)
        at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsMultiStatus(DavMethodBase.java:91)
        at net.fortuna.ical4j.connector.dav.CalDavCalendarStore.getCollection(CalDavCalendarStore.java:157)
```

Why would `jackrabbit.webdav` be generating a "Service Unavailable" exception? Is there more than one way the CalDAV protocol can retrieve calendars, thus meaning that DAVX5 works but BORG/ical4j doesn't...?

**Comment by mikeberger** [comment]
It works fine with nextcloud version 15. I tested with similar punctuation in the user name in case that was the problem.
Your nextcloud is version 18. 

I am 2 releases behind on the ical4j-connector. I can try updating to the latest version. It looks like the jackrabbit lib used by my ical4j version is also behind. I can build a version with the new ical4j and see if it helps. I'd be surprised if it helps though. there are no commits for ical4j that mention fixing some kind of bug like this.
