### ISSUE TITLE
java.lang.NullPointerException When Sync-ing with CALDAV

### ISSUE THREAD

**Issue by ecxod** [mikeberger/borg_calendar#90]
When I sync with my Baikal CalDav Server I get a java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/10009595/88003618-9303db80-cb05-11ea-86fc-b3f34c42b828.png)

I get this Window 30 to 50 times, I have not counted ..

Syncing....Please wait
SYNC: connect to https://dav.zp1.net/
SYNC: Process 0 Outgoing Items
SYNC: Start Incoming Sync
SYNC: found 38 Event Calendars on server
SYNC: processed 15 new/changed Events
SYNC: found 55 Todo Calendars on server
SYNC: processed 42 new/changed Tasks
SYNC: check for deletes
SYNC: Process 0 Outgoing Items
Fertig

**Comment by mikeberger** [comment]
Please send the full error stack trace for a few of the errors. They should be in %USERPROFILE%\.borg.log

If it is not there, then turn on the stack trace option:

![image](https://user-images.githubusercontent.com/6563665/88101071-77cbb700-cb6b-11ea-8d89-588b00f88f95.png)

**Comment by mikeberger** [comment]
please reopen if you can get a stack trace of the exception.
