### ISSUE TITLE
unable to install with borg_installer_linux

### ISSUE THREAD

**Issue by DougBain** [mikeberger/borg_calendar#95]
I'm trying to install borg on a new PC running Linux Mint Mate 20 - my old 1.8.3 installation doesn't work on it.
I've downloaded borg_installer_linux_19.tar.gz, unpacked it, entered the borg_installer directory and run 
java -jar borg_installer-1.9.jar.
This gets to 'select installation packages'; I allow Base and JRE to be selected, then 'Next'.
Installation crashes with these messages:
Caused by: java.lang.NullPointerException: null
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.>
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.>
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.>
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.>
in com.izforge.izpack.installer.unpacker.UnpackerBase.extract() at UnpackerBase>
in com.izforge.izpack.installer.unpacker.LooseFileUnpacker.unpack() at LooseFil>
in java.io.File. () at File.java:361
What's wrong and how do I install borg correctly?

**Comment by DougBain** [comment]
please e-mail to douglas.bainbridge@cantab.net. My registered e-mail address is not working.

**Comment by mikeberger** [comment]
That's a bug in the installer, which is not my code.

I don't have a problem with Mint 19.

Make sure you run with the included JRE:  ./jre/bin/java -jar borg_installer-1.9.jar 

I don't know what the bug is. Are there spaces or special chars in your install path name or in the path where the installer is run from? If so, then use different dirs.

The installer is mainly unzipping a zip file. As a last resort, I could just provide the ZIP file.

**Comment by DougBain** [comment]
Thanks.  I ran ./jre/bin/java -jar borg_installer-1.9.jar from the 
borg_installer folder with some progress but eventual failure.

command line output:

./jre/bin/java -jar borg_installer-1.9.jar
Command line arguments:
WARNING: No locale for: fra
WARNING: No locale for: spa
WARNING: No locale for: deu
WARNING: No locale for: ita
WARNING: No locale for: nld
WARNING: No locale for: pol
WARNING: No locale for: prt
WARNING: No locale for: rus
WARNING: No locale for: chn
WARNING: No locale for: ukr
Cannot find named resource: 'packsLang.xml' AND 'packsLang.xml_eng'
====================
Installation started
Framework: 5.1.3-84aaf (IzPack)
Platform: 
ubuntu_linux,version=5.4.0-52-generic,arch=x64,symbolicName=null,javaVersion=13.0.2
Cleaning up the target folder ...
SEVERE: Failed to unpack pack: JRE

program output:

com.izforge.izpack.api.exception.IzPackException: An error occured
in java.lang.Thread.run() at Thread.java:830
in com.izforge.izpack.installer.unpacker.UnpackerBase.run() at 
UnpackerBase.java:241
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at 
UnpackerBase.java:319
Caused by: java.lang.NullPointerException: null
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at 
UnpackerBase.java:299
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at 
UnpackerBase.java:475
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at 
UnpackerBase.java:528
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at 
UnpackerBase.java:627
in com.izforge.izpack.installer.unpacker.UnpackerBase.extract() at 
UnpackerBase.java:673
in com.izforge.izpack.installer.unpacker.LooseFileUnpacker.unpack() at 
LooseFileUnpacker.java:92
in java.io.File. () at File.java:359

installation output: Step 6 of 8

pack installation progress: finished

overall installation progress: 2/2


Doug

**Comment by mikeberger** [comment]
Just download the attached borg.zip,unzip it, and run borg.jar with the jre that came with the installer.
On linux, the installer doesn't do much more than simply unzipping this file to the folder of your choice.

[borg.zip](https://github.com/mikeberger/borg_calendar/files/5491032/borg.zip)

**Comment by DougBain** [comment]
Thanks, that does the trick.

However, I see these command-line warnings afterwards. Are they anything 
to be concerned about?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by 
com.jgoodies.looks.common.RenderingUtils 
(file:/home/doug/downloads/borg_installer/lib/looks-2.2.2.jar) to method 
sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of 
com.jgoodies.looks.common.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal 
reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by mikeberger** [comment]
Those warnings are harmless

**Comment by DougBain** [comment]
I'm ignoring the warnings as advised.

I have copied borgdb.h2.db and borgdb.trace.db from my old Calendar, but 
I have a residual problem.

With the old Borg, I marked completed ToDos with Done (no delete) and 
they showed up with strikethrough on the Calendar. Now, the Calendar 
shows none of the completed ToDos on the Calendar, only the upcoming 
ToDos on the ToDo list.

How do I get these shown?

**Comment by mikeberger** [comment]
Uncheck the Hide Strike-through Items option on the Appearance options tab under the preferences.

The preferences are not in the database. They are stored locally on each machine.

**Comment by DougBain** [comment]
It's already unchecked, but no strike-throughs are visible

**Comment by mikeberger** [comment]
Is your background black? Strike-throughs are hard-coded to be black (a buggy design choice).

Do you see them when you hover the mouse over the spot where they should be?

Are you showing all categories of appointments?

**Comment by DougBain** [comment]
Background is white.

Nothing visible when hovering over dates with done todos.

All categories are selected for display.

Unexpired todos don't show up on the calendar, nor do new ones entered 
now (they appear on the Todo list as normal)

**Comment by mikeberger** [comment]
open the appt editor to add a new appointment. This will show the default appt settings.  Is the category defaulting to <No Category>? Is the Private checkbox checked?

**Comment by DougBain** [comment]
category defaults to <No category>

Private checkbox is unchecked.

**Comment by mikeberger** [comment]
I've been unable to recreate the problem on Mint Mate 20 using the same borg.zip and jre.

I just want to make sure that you are talking about simple todo's and not tasks? right? This behavior can happen with tasks if you don't set the option to display tasks on the calendar, but I can't see what would cause todos to not show besides some kind of bug.

Are there any errors in ~/.borg.log or ~/.borg.out???

**Comment by DougBain** [comment]
I've now tried 1.9.0 via the installer jre and your borg.zip with Linux Mint Debian 4 on a laptop - it works fine, with the new todos and the old ones struck-through appearing on the calendar.
I've also tried it on a laptop with a Linux Mint 20 installation. This works too. Evidently something on my PC Mint 20 is interfering with the proper display. Can you suggest where I might start to try and track it down?

**Comment by mikeberger** [comment]
You can try changing the month view font. Also look in ~/.xsession-errors to see if some kind of drawing issue is being reported.
You can download a newer jdk from https://openjdk.java.net/ and see if that changes something. Maybe there was a bug in the jdk?
You can fiddle with the linux look and feel seetings as well.

**Comment by DougBain** [comment]
(1) changing month view font - no difference.
(2) .xession-errors -  these appeared on starting Borg:  Does anything here look like a drawing issue?
.....................................
qt5ct: palette support is disabled
kf5.kdbusaddons: Can not find 'kdeinit5' executable at  "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" "/usr/bin, /usr/lib/qt5/bin"
kf5.kservice.services: KServiceTypeTrader: serviceType "ThumbCreator" not found
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Mint-Y/apps/16/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Mint-Y/apps/16@2x/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Mint-Y/mimetypes/16/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Mint-Y/mimetypes/16@2x/"
also Invalid Context for Apps and Mimetypes lines for icon themes: 22/" 22@2x/" 24/" 24@2x/" 32/" 32@2x/" 48/" 48@2x/" 64/" 64@2x/" 96/" 96@2x/" 128/" 128@2x/" 256/" 256@2x/" symbolic/"

and Invalid Context for Legacy and UI icon themes:
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/" 16x16/legacy/" 22x22/legacy/" 24x24/legacy/" 32x32/legacy/" 48x48/legacy/" /64x64/ui/" 96x96/legacy/" 256x256/legacy/" 512x512/legacy/" scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/" 24x24/ui/" 32x32/ui/" 48x48/ui/" 64x64/ui/" 96x96/ui/" scalable/ui/"

Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
sonnet.plugins.hspell: HSpellDict::HSpellDict: Init failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4200006 (Untitled  )
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
.........................................

(3) I untarred an openjdk-15.0.1.tar.gz in a folder, copied your borg.jar into it, and ran 
./bin/java -jar borg.jar
getting the error message 
"Error: Could not find or load main class net.sf.borg.control.Borg
Caused by: java.lang.NoClassDefFoundError: net/sf/borg/common/SocketHandler".
I'm unfamiliar with java, so what should I have done?
:

**Comment by mikeberger** [comment]
.xession-errors has nothing of interest.

you don't need to copy anything. You can run: <path to jdk>/bin/java -jar borg.jar

If you want to copy the program, you need to copy the lib folder as well.

**Comment by mikeberger** [comment]
I'm trying to replace IzPack with jpackage for installation. A deb installer is available for linux.

https://github.com/mikeberger/borg_calendar/releases/tag/1.9.0.2
