### ISSUE TITLE
Nonfatal error when running Borg from terminal

### ISSUE THREAD

**Issue by gitthepie** [mikeberger/borg_calendar#97]
This was a nonfatal error, but I got this message when running the Borg shell script from terminal on Linux Mint 20 Ulyana:

$ ./run_borg.sh

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.looks.common.RenderingUtils (file:/home/[REDACTED USERNAME]/BORGCalendar/lib/looks-2.2.2.jar) to method sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.looks.common.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I don't think the error is critical because Borg still ran normally, but the error seems to hint that something may break in the future.

**Comment by mikeberger** [comment]
not a problem. the default look and feel that is used (JGoodies looks) is no longer maintained. At some point in the future, Java may be changed in a way that breaks it. 

If I ever switch to a future version of Java that breaks this, I will just remove this look and feel and default to one of the ones that comes with Java.
